// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package types

// TargetJobStatus mirrors shared/conventions.yaml sourceSection 5.1 (jsonField: "status").
type TargetJobStatus string

const (
	TargetJobStatusDraft        TargetJobStatus = "draft"
	TargetJobStatusPreparing    TargetJobStatus = "preparing"
	TargetJobStatusApplied      TargetJobStatus = "applied"
	TargetJobStatusInterviewing TargetJobStatus = "interviewing"
	TargetJobStatusOffer        TargetJobStatus = "offer"
	TargetJobStatusRejected     TargetJobStatus = "rejected"
	TargetJobStatusArchived     TargetJobStatus = "archived"
)

// AllTargetJobStatuses lists every defined value in declaration order.
var AllTargetJobStatuses = []TargetJobStatus{
	TargetJobStatusDraft,
	TargetJobStatusPreparing,
	TargetJobStatusApplied,
	TargetJobStatusInterviewing,
	TargetJobStatusOffer,
	TargetJobStatusRejected,
	TargetJobStatusArchived,
}

// TargetJobParseStatus mirrors shared/conventions.yaml sourceSection 5.2 (jsonField: "parseStatus").
type TargetJobParseStatus string

const (
	TargetJobParseStatusQueued     TargetJobParseStatus = "queued"
	TargetJobParseStatusProcessing TargetJobParseStatus = "processing"
	TargetJobParseStatusReady      TargetJobParseStatus = "ready"
	TargetJobParseStatusFailed     TargetJobParseStatus = "failed"
)

// AllTargetJobParseStatuses lists every defined value in declaration order.
var AllTargetJobParseStatuses = []TargetJobParseStatus{
	TargetJobParseStatusQueued,
	TargetJobParseStatusProcessing,
	TargetJobParseStatusReady,
	TargetJobParseStatusFailed,
}

// PracticeMode mirrors shared/conventions.yaml sourceSection 5.3 (jsonField: "mode").
type PracticeMode string

const (
	PracticeModeAssisted PracticeMode = "assisted"
	PracticeModeStrict   PracticeMode = "strict"
)

// AllPracticeModes lists every defined value in declaration order.
var AllPracticeModes = []PracticeMode{
	PracticeModeAssisted,
	PracticeModeStrict,
}

// PracticeGoal mirrors shared/conventions.yaml sourceSection 5.4 (jsonField: "goal").
type PracticeGoal string

const (
	PracticeGoalBaseline          PracticeGoal = "baseline"
	PracticeGoalRetryCurrentRound PracticeGoal = "retry_current_round"
	PracticeGoalNextRound         PracticeGoal = "next_round"
)

// AllPracticeGoals lists every defined value in declaration order.
var AllPracticeGoals = []PracticeGoal{
	PracticeGoalBaseline,
	PracticeGoalRetryCurrentRound,
	PracticeGoalNextRound,
}

// InterviewerRole mirrors shared/conventions.yaml sourceSection 5.5 (jsonField: "interviewerRole").
type InterviewerRole string

const (
	InterviewerRoleGeneralist       InterviewerRole = "generalist"
	InterviewerRoleHr               InterviewerRole = "hr"
	InterviewerRoleHiringManager    InterviewerRole = "hiring_manager"
	InterviewerRoleTechnicalManager InterviewerRole = "technical_manager"
	InterviewerRolePeer             InterviewerRole = "peer"
)

// AllInterviewerRoles lists every defined value in declaration order.
var AllInterviewerRoles = []InterviewerRole{
	InterviewerRoleGeneralist,
	InterviewerRoleHr,
	InterviewerRoleHiringManager,
	InterviewerRoleTechnicalManager,
	InterviewerRolePeer,
}

// SessionStatus mirrors shared/conventions.yaml sourceSection 5.6 (jsonField: "sessionStatus").
type SessionStatus string

const (
	SessionStatusQueued           SessionStatus = "queued"
	SessionStatusRunning          SessionStatus = "running"
	SessionStatusWaitingUserInput SessionStatus = "waiting_user_input"
	SessionStatusCompleting       SessionStatus = "completing"
	SessionStatusCompleted        SessionStatus = "completed"
	SessionStatusFailed           SessionStatus = "failed"
	SessionStatusCancelled        SessionStatus = "cancelled"
)

// AllSessionStatuses lists every defined value in declaration order.
var AllSessionStatuses = []SessionStatus{
	SessionStatusQueued,
	SessionStatusRunning,
	SessionStatusWaitingUserInput,
	SessionStatusCompleting,
	SessionStatusCompleted,
	SessionStatusFailed,
	SessionStatusCancelled,
}

// ReportStatus mirrors shared/conventions.yaml sourceSection 5.7 (jsonField: "reportStatus").
type ReportStatus string

const (
	ReportStatusQueued     ReportStatus = "queued"
	ReportStatusGenerating ReportStatus = "generating"
	ReportStatusReady      ReportStatus = "ready"
	ReportStatusFailed     ReportStatus = "failed"
)

// AllReportStatuses lists every defined value in declaration order.
var AllReportStatuses = []ReportStatus{
	ReportStatusQueued,
	ReportStatusGenerating,
	ReportStatusReady,
	ReportStatusFailed,
}

// ReadinessTier mirrors shared/conventions.yaml sourceSection 5.8 (jsonField: "readinessTier").
type ReadinessTier string

const (
	ReadinessTierNotReady       ReadinessTier = "not_ready"
	ReadinessTierNeedsPractice  ReadinessTier = "needs_practice"
	ReadinessTierBasicallyReady ReadinessTier = "basically_ready"
	ReadinessTierWellPrepared   ReadinessTier = "well_prepared"
)

// AllReadinessTiers lists every defined value in declaration order.
var AllReadinessTiers = []ReadinessTier{
	ReadinessTierNotReady,
	ReadinessTierNeedsPractice,
	ReadinessTierBasicallyReady,
	ReadinessTierWellPrepared,
}

// DimensionStatus mirrors shared/conventions.yaml sourceSection 5.9 (jsonField: "dimensionStatus").
type DimensionStatus string

const (
	DimensionStatusStrong    DimensionStatus = "strong"
	DimensionStatusMeetsBar  DimensionStatus = "meets_bar"
	DimensionStatusNeedsWork DimensionStatus = "needs_work"
)

// AllDimensionStatuses lists every defined value in declaration order.
var AllDimensionStatuses = []DimensionStatus{
	DimensionStatusStrong,
	DimensionStatusMeetsBar,
	DimensionStatusNeedsWork,
}

// Confidence mirrors shared/conventions.yaml sourceSection 5.10 (jsonField: "confidence").
type Confidence string

const (
	ConfidenceHigh   Confidence = "high"
	ConfidenceMedium Confidence = "medium"
	ConfidenceLow    Confidence = "low"
)

// AllConfidences lists every defined value in declaration order.
var AllConfidences = []Confidence{
	ConfidenceHigh,
	ConfidenceMedium,
	ConfidenceLow,
}

// QuestionReviewStatus mirrors shared/conventions.yaml sourceSection 5.11 (jsonField: "questionReviewStatus").
type QuestionReviewStatus string

const (
	QuestionReviewStatusOpen           QuestionReviewStatus = "open"
	QuestionReviewStatusQueuedForRetry QuestionReviewStatus = "queued_for_retry"
	QuestionReviewStatusResolved       QuestionReviewStatus = "resolved"
)

// AllQuestionReviewStatuses lists every defined value in declaration order.
var AllQuestionReviewStatuses = []QuestionReviewStatus{
	QuestionReviewStatusOpen,
	QuestionReviewStatusQueuedForRetry,
	QuestionReviewStatusResolved,
}

// PrivacyRequestType mirrors shared/conventions.yaml sourceSection 5.13 (jsonField: "privacyRequestType").
type PrivacyRequestType string

const (
	PrivacyRequestTypeExport PrivacyRequestType = "export"
	PrivacyRequestTypeDelete PrivacyRequestType = "delete"
)

// AllPrivacyRequestTypes lists every defined value in declaration order.
var AllPrivacyRequestTypes = []PrivacyRequestType{
	PrivacyRequestTypeExport,
	PrivacyRequestTypeDelete,
}

// PrivacyRequestStatus mirrors shared/conventions.yaml sourceSection 5.13 (jsonField: "privacyRequestStatus").
type PrivacyRequestStatus string

const (
	PrivacyRequestStatusQueued     PrivacyRequestStatus = "queued"
	PrivacyRequestStatusProcessing PrivacyRequestStatus = "processing"
	PrivacyRequestStatusCompleted  PrivacyRequestStatus = "completed"
	PrivacyRequestStatusFailed     PrivacyRequestStatus = "failed"
	PrivacyRequestStatusCancelled  PrivacyRequestStatus = "cancelled"
)

// AllPrivacyRequestStatuses lists every defined value in declaration order.
var AllPrivacyRequestStatuses = []PrivacyRequestStatus{
	PrivacyRequestStatusQueued,
	PrivacyRequestStatusProcessing,
	PrivacyRequestStatusCompleted,
	PrivacyRequestStatusFailed,
	PrivacyRequestStatusCancelled,
}

// JobStatus mirrors shared/conventions.yaml sourceSection 4.2 (jsonField: "status").
type JobStatus string

const (
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed    JobStatus = "failed"
	JobStatusCancelled JobStatus = "cancelled"
	JobStatusDead      JobStatus = "dead"
)

// AllJobStatuses lists every defined value in declaration order.
var AllJobStatuses = []JobStatus{
	JobStatusQueued,
	JobStatusRunning,
	JobStatusSucceeded,
	JobStatusFailed,
	JobStatusCancelled,
	JobStatusDead,
}
