// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package types

// Cursor pagination defaults from shared/conventions.yaml.
const (
	DefaultPageSize = 20
	MaxPageSize     = 100
)

// IdempotencyKeyTTLSeconds is the B1-documented 24h TTL.
const IdempotencyKeyTTLSeconds = 86400

// PageInfo is the B1 cursor pagination wire shape.
type PageInfo struct {
	NextCursor *string `json:"nextCursor"`
	PageSize   int     `json:"pageSize"`
	HasMore    bool    `json:"hasMore"`
}
