// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package types

// Cursor pagination defaults (00-shared-conventions §3.3).
const (
	DefaultPageSize = 20
	MaxPageSize     = 100
)

// IdempotencyKeyTTLSeconds is the documented 24h TTL (00-shared-conventions §3.4).
const IdempotencyKeyTTLSeconds = 86400

// PageInfo is the cursor pagination wire shape (00-shared-conventions §3.1).
type PageInfo struct {
	NextCursor *string `json:"nextCursor"`
	PageSize   int     `json:"pageSize"`
	HasMore    bool    `json:"hasMore"`
}
