// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml and shared/jobs.yaml — owned by docs/spec/event-and-outbox-contract.

package events

import (
	"encoding/json"
	"time"
)

type EventName string

type Producer string

const (
	ProducerApi        Producer = "api"
	ProducerDispatcher Producer = "dispatcher"
	ProducerReview     Producer = "review"
	ProducerWorker     Producer = "worker"
)

type Envelope struct {
	EventID       string          `json:"eventId"`
	EventName     EventName       `json:"eventName"`
	EventVersion  int             `json:"eventVersion"`
	AggregateType string          `json:"aggregateType"`
	AggregateID   string          `json:"aggregateId"`
	OccurredAt    time.Time       `json:"occurredAt"`
	Producer      Producer        `json:"producer"`
	TraceID       *string         `json:"traceId,omitempty"`
	Payload       json.RawMessage `json:"payload"`
}

func (e Envelope) MarshalJSON() ([]byte, error) {
	type alias Envelope
	return json.Marshal(alias(e))
}

func (e *Envelope) UnmarshalJSON(data []byte) error {
	type alias Envelope
	var decoded alias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*e = Envelope(decoded)
	return nil
}
