// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml, shared/jobs.yaml, and shared/conventions.yaml — owned by docs/spec/event-and-outbox-contract.

package events

import sharedtypes "github.com/monshunter/easyinterview/backend/internal/shared/types"

type ResumeTailorMode string

const (
	ResumeTailorModeGapReview         ResumeTailorMode = "gap_review"
	ResumeTailorModeBulletSuggestions ResumeTailorMode = "bullet_suggestions"
)

const (
	EventNameTargetImportRequested     EventName = "target.import.requested"
	EventNameTargetParsed              EventName = "target.parsed"
	EventNameTargetAnalysisFailed      EventName = "target.analysis.failed"
	EventNamePracticeSessionStarted    EventName = "practice.session.started"
	EventNamePracticeSessionCompleted  EventName = "practice.session.completed"
	EventNameReportGenerationRequested EventName = "report.generation.requested"
	EventNameReportGenerated           EventName = "report.generated"
	EventNameReportGenerationFailed    EventName = "report.generation.failed"
	EventNameResumeParseCompleted      EventName = "resume.parse.completed"
	EventNameResumeTailorCompleted     EventName = "resume.tailor.completed"
	EventNamePrivacyRequestCreated     EventName = "privacy.request.created"
	EventNamePrivacyRequestCompleted   EventName = "privacy.request.completed"
)

type TargetImportRequestedPayload struct {
	TargetJobID    string `json:"targetJobId"`
	TargetLanguage string `json:"targetLanguage"`
	UserID         string `json:"userId"`
}

type TargetParsedPayload struct {
	AnalysisStatus   sharedtypes.TargetJobParseStatus `json:"analysisStatus"`
	CoreThemes       []string                         `json:"coreThemes"`
	RequirementCount int                              `json:"requirementCount"`
	TargetJobID      string                           `json:"targetJobId"`
	UserID           string                           `json:"userId"`
}

type TargetAnalysisFailedPayload struct {
	ErrorCode   string `json:"errorCode"`
	Retryable   bool   `json:"retryable"`
	TargetJobID string `json:"targetJobId"`
}

type PracticeSessionStartedPayload struct {
	Goal        sharedtypes.PracticeGoal `json:"goal"`
	Language    string                   `json:"language"`
	PlanID      string                   `json:"planId"`
	SessionID   string                   `json:"sessionId"`
	TargetJobID string                   `json:"targetJobId"`
}

type PracticeSessionCompletedPayload struct {
	Language    string `json:"language"`
	PlanID      string `json:"planId"`
	SessionID   string `json:"sessionId"`
	TargetJobID string `json:"targetJobId"`
}

type ReportGenerationRequestedPayload struct {
	ReportID    string `json:"reportId"`
	SessionID   string `json:"sessionId"`
	TargetJobID string `json:"targetJobId"`
}

type ReportGeneratedPayload struct {
	ModelID           string                    `json:"modelId"`
	PreparednessLevel sharedtypes.ReadinessTier `json:"preparednessLevel"`
	PromptVersion     string                    `json:"promptVersion"`
	ReportID          string                    `json:"reportId"`
	RubricVersion     string                    `json:"rubricVersion"`
	SessionID         string                    `json:"sessionId"`
	TargetJobID       string                    `json:"targetJobId"`
}

type ReportGenerationFailedPayload struct {
	ErrorCode string `json:"errorCode"`
	ReportID  string `json:"reportId"`
	Retryable bool   `json:"retryable"`
	SessionID string `json:"sessionId"`
}

type ResumeParseCompletedPayload struct {
	ParseStatus sharedtypes.TargetJobParseStatus `json:"parseStatus"`
	ResumeID    string                           `json:"resumeId"`
	UserID      string                           `json:"userId"`
}

type ResumeTailorCompletedPayload struct {
	Mode        ResumeTailorMode         `json:"mode"`
	ResumeID    string                   `json:"resumeId"`
	Status      sharedtypes.ReportStatus `json:"status"`
	TailorRunID string                   `json:"tailorRunId"`
	TargetJobID string                   `json:"targetJobId"`
}

type PrivacyRequestCreatedPayload struct {
	PrivacyRequestID string                         `json:"privacyRequestId"`
	RequestType      sharedtypes.PrivacyRequestType `json:"requestType"`
	UserID           string                         `json:"userId"`
}

type PrivacyRequestCompletedPayload struct {
	PrivacyRequestID string                           `json:"privacyRequestId"`
	RequestType      sharedtypes.PrivacyRequestType   `json:"requestType"`
	Status           sharedtypes.PrivacyRequestStatus `json:"status"`
	UserID           string                           `json:"userId"`
}
