// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml, shared/jobs.yaml, and shared/conventions.yaml — owned by docs/spec/event-and-outbox-contract.

package jobs

import "fmt"

type JobType string

type AsynqTask string

type JobTriggerEventSemantic string

const (
	JobTypeTargetImport    JobType = "target_import"
	JobTypeResumeParse     JobType = "resume_parse"
	JobTypeReportGenerate  JobType = "report_generate"
	JobTypeResumeTailor    JobType = "resume_tailor"
	JobTypeDebriefGenerate JobType = "debrief_generate"
	JobTypeSourceRefresh   JobType = "source_refresh"
	JobTypePrivacyExport   JobType = "privacy_export"
	JobTypePrivacyDelete   JobType = "privacy_delete"
	JobTypeEmailDispatch   JobType = "email_dispatch"
)

const (
	AsynqTaskTargetImport    AsynqTask = "target.import"
	AsynqTaskResumeParse     AsynqTask = "resume.parse"
	AsynqTaskReportGenerate  AsynqTask = "report.generate"
	AsynqTaskResumeTailor    AsynqTask = "resume.tailor"
	AsynqTaskDebriefGenerate AsynqTask = "debrief.generate"
	AsynqTaskSourceRefresh   AsynqTask = "source.refresh"
	AsynqTaskPrivacyExport   AsynqTask = "privacy.export"
	AsynqTaskPrivacyDelete   AsynqTask = "privacy.delete"
	AsynqTaskEmailDispatch   AsynqTask = "email.dispatch"
)

const (
	JobTriggerEventSemanticTriggerCreatesJob JobTriggerEventSemantic = "trigger_creates_job"
	JobTriggerEventSemanticSourceEventOnly   JobTriggerEventSemantic = "source_event_only"
)

var JobTriggerEventSemantics = map[JobType]JobTriggerEventSemantic{
	JobTypeTargetImport:    JobTriggerEventSemanticTriggerCreatesJob,
	JobTypeResumeParse:     JobTriggerEventSemanticTriggerCreatesJob,
	JobTypeReportGenerate:  JobTriggerEventSemanticSourceEventOnly,
	JobTypeResumeTailor:    JobTriggerEventSemanticTriggerCreatesJob,
	JobTypeDebriefGenerate: JobTriggerEventSemanticTriggerCreatesJob,
	JobTypeSourceRefresh:   JobTriggerEventSemanticTriggerCreatesJob,
	JobTypePrivacyExport:   JobTriggerEventSemanticTriggerCreatesJob,
	JobTypePrivacyDelete:   JobTriggerEventSemanticTriggerCreatesJob,
	JobTypeEmailDispatch:   JobTriggerEventSemanticTriggerCreatesJob,
}

func IsSourceEventOnly(jobType JobType) bool {
	return JobTriggerEventSemantics[jobType] == JobTriggerEventSemanticSourceEventOnly
}

var APIFacingJobTypes = []JobType{
	JobTypeTargetImport,
	JobTypeResumeParse,
	JobTypeReportGenerate,
	JobTypeResumeTailor,
	JobTypeDebriefGenerate,
	JobTypePrivacyExport,
	JobTypePrivacyDelete,
}

var EmailDispatchAllowedPayloadFields = []string{
	"authChallengeId",
	"dedupeKey",
	"deliverySecretRef",
	"locale",
	"templateKey",
	"userId",
}

var EmailDispatchRedactedFields = []string{
	"rawMagicLinkToken",
	"magicLinkUrl",
	"recipientEmail",
	"recipientEmailHash",
	"emailBody",
	"emailSubject",
}

type EmailDispatchPayload map[string]string

func BuildEmailDispatchPayload(input map[string]string) (EmailDispatchPayload, error) {
	allowed := map[string]struct{}{
		"authChallengeId":   {},
		"dedupeKey":         {},
		"deliverySecretRef": {},
		"locale":            {},
		"templateKey":       {},
		"userId":            {},
	}
	redacted := map[string]struct{}{
		"rawMagicLinkToken":  {},
		"magicLinkUrl":       {},
		"recipientEmail":     {},
		"recipientEmailHash": {},
		"emailBody":          {},
		"emailSubject":       {},
	}
	payload := make(EmailDispatchPayload, len(input))
	for field, value := range input {
		if _, forbidden := redacted[field]; forbidden {
			return nil, fmt.Errorf("email_dispatch payload field %s is redacted and forbidden", field)
		}
		if _, ok := allowed[field]; !ok {
			return nil, fmt.Errorf("email_dispatch payload field %s is not allowed", field)
		}
		payload[field] = value
	}
	return payload, nil
}
