// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml and shared/jobs.yaml — owned by docs/spec/event-and-outbox-contract.

package jobs

type JobType string

type AsynqTask string

const (
	JobTypeTargetImport    JobType = "target_import"
	JobTypeResumeParse     JobType = "resume_parse"
	JobTypeReportGenerate  JobType = "report_generate"
	JobTypeResumeTailor    JobType = "resume_tailor"
	JobTypeDebriefGenerate JobType = "debrief_generate"
	JobTypeSourceRefresh   JobType = "source_refresh"
	JobTypeEmbeddingUpsert JobType = "embedding_upsert"
	JobTypePrivacyExport   JobType = "privacy_export"
	JobTypePrivacyDelete   JobType = "privacy_delete"
	JobTypeEmailDispatch   JobType = "email_dispatch"
)

const (
	AsynqTaskTargetImport    AsynqTask = "target.import"
	AsynqTaskResumeParse     AsynqTask = "resume.parse"
	AsynqTaskReportGenerate  AsynqTask = "report.generate"
	AsynqTaskResumeTailor    AsynqTask = "resume.tailor"
	AsynqTaskDebriefGenerate AsynqTask = "debrief.generate"
	AsynqTaskSourceRefresh   AsynqTask = "source.refresh"
	AsynqTaskEmbeddingUpsert AsynqTask = "embedding.upsert"
	AsynqTaskPrivacyExport   AsynqTask = "privacy.export"
	AsynqTaskPrivacyDelete   AsynqTask = "privacy.delete"
	AsynqTaskEmailDispatch   AsynqTask = "email.dispatch"
)

var APIFacingJobTypes = []JobType{
	JobTypeTargetImport,
	JobTypeResumeParse,
	JobTypeReportGenerate,
	JobTypeResumeTailor,
	JobTypeDebriefGenerate,
	JobTypePrivacyExport,
	JobTypePrivacyDelete,
}

var EmailDispatchAllowedPayloadFields = []string{
	"authChallengeId",
	"dedupeKey",
	"deliverySecretRef",
	"locale",
	"templateKey",
	"userId",
}

var EmailDispatchRedactedFields = []string{
	"rawMagicLinkToken",
	"magicLinkUrl",
	"recipientEmail",
	"recipientEmailHash",
	"emailBody",
	"emailSubject",
}
