#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
OUTPUT_DIR="$REPO_ROOT/.test-output/e2e/p0-069-debrief-pixel-parity-and-legacy-negative"
LOG_FILE="$OUTPUT_DIR/trigger.log"
test -s "$LOG_FILE"
grep -Fq "E2E.P0.069 RUNNER pnpm vitest" "$LOG_FILE"
grep -Fq "E2E.P0.069 RUNNER playwright debrief pixel parity" "$LOG_FILE"
grep -Eq "Tests[[:space:]]+[0-9]+ passed" "$LOG_FILE"
grep -Fq "tests/pixel-parity/debrief.spec.ts" "$LOG_FILE"
grep -Eq "[0-9]+ passed" "$LOG_FILE"
grep -Fq "frontend-debrief legacy lint OK" "$LOG_FILE"
grep -Fq "SCENARIO TREE LEGACY GREP CLEAN" "$LOG_FILE"
grep -Eq "debriefI18nCoverage.test.ts" "$LOG_FILE"
grep -Eq "privacyBoundary.test.ts" "$LOG_FILE"
! grep -Eq "no tests" "$LOG_FILE"
! grep -Eq "Tests[[:space:]]+[0-9]+ failed" "$LOG_FILE"
! grep -Eq "[0-9]+ failed" "$LOG_FILE"
echo "E2E.P0.069 PASS"
