package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// repoRootForTest walks up from the test working dir to the easyinterview repo root.
// The test binary runs in backend/cmd/codegen/conventions, so repo root is 4 dirs up.
func repoRootForTest(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	return filepath.Clean(filepath.Join(wd, "..", "..", "..", ".."))
}

func loadYAML(t *testing.T) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(repoRootForTest(t), "shared", "conventions.yaml"))
	if err != nil {
		t.Fatalf("read conventions.yaml: %v", err)
	}
	return data
}

func TestRunFromBytes_GeneratesAllExpectedFiles(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}

	expected := []string{
		"backend/internal/shared/types/enums.go",
		"backend/internal/shared/types/http_dto.go",
		"backend/internal/shared/errors/codes.go",
		"backend/internal/shared/idx/generated.go",
		"backend/internal/shared/ai/vocabulary.go",
		"frontend/src/lib/conventions/enums.ts",
		"frontend/src/lib/conventions/errors.ts",
		"frontend/src/lib/conventions/ai.ts",
		"frontend/src/lib/conventions/pagination.ts",
		"frontend/src/lib/ids/generated.ts",
	}
	for _, rel := range expected {
		if _, err := os.Stat(filepath.Join(tmp, rel)); err != nil {
			t.Errorf("missing %s: %v", rel, err)
		}
	}
}

func TestRunFromBytes_Idempotent(t *testing.T) {
	tmp := t.TempDir()
	yaml := loadYAML(t)

	if err := RunFromBytes(yaml, tmp, false); err != nil {
		t.Fatalf("first run: %v", err)
	}
	first := readAllGenerated(t, tmp)

	if err := RunFromBytes(yaml, tmp, false); err != nil {
		t.Fatalf("second run: %v", err)
	}
	second := readAllGenerated(t, tmp)

	if len(first) != len(second) {
		t.Fatalf("file set drift: first=%d second=%d", len(first), len(second))
	}
	for path, want := range first {
		got, ok := second[path]
		if !ok {
			t.Errorf("missing %s on second run", path)
			continue
		}
		if !bytes.Equal(got, want) {
			t.Errorf("idempotency broken for %s", path)
		}
	}
}

func TestRunFromBytes_WriteIfChangedSkipsUnchanged(t *testing.T) {
	tmp := t.TempDir()
	yaml := loadYAML(t)

	if err := RunFromBytes(yaml, tmp, false); err != nil {
		t.Fatalf("first run: %v", err)
	}
	target := filepath.Join(tmp, "backend/internal/shared/types/enums.go")
	info1, err := os.Stat(target)
	if err != nil {
		t.Fatalf("stat 1: %v", err)
	}
	mtime1 := info1.ModTime()

	// Sleep barrier removed: second run should skip write entirely when content matches,
	// so mtime stays equal regardless of clock granularity.
	if err := RunFromBytes(yaml, tmp, false); err != nil {
		t.Fatalf("second run: %v", err)
	}
	info2, err := os.Stat(target)
	if err != nil {
		t.Fatalf("stat 2: %v", err)
	}
	if !info2.ModTime().Equal(mtime1) {
		t.Errorf("expected mtime to be preserved on idempotent re-run; got %v vs %v", info2.ModTime(), mtime1)
	}
}

func TestRenderGoEnums_KnownConstants(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}

	src := readFile(t, filepath.Join(tmp, "backend/internal/shared/types/enums.go"))
	must := []string{
		"// Code generated by",
		"package types",
		"type PracticeMode string",
		`PracticeMode = "core_interview"`,
		"type SessionStatus string",
		`SessionStatus = "waiting_user_input"`,
		"type JobStatus string",
		`JobStatus = "dead"`,
		"type PrivacyRequestType string",
		"type PrivacyRequestStatus string",
		"var AllPracticeModes = []PracticeMode{",
		"var AllSessionStatuses = []SessionStatus{",
		"var AllJobStatuses = []JobStatus{",
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("enums.go missing %q", want)
		}
	}
}

func TestRenderGoErrorCodes_AllSixCodes(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}

	src := readFile(t, filepath.Join(tmp, "backend/internal/shared/errors/codes.go"))
	must := []string{
		"package errors",
		`CodeAuthUnauthorized`,
		`= "AUTH_UNAUTHORIZED"`,
		`CodeRateLimited`,
		`= "RATE_LIMITED"`,
		`CodeValidationFailed`,
		`= "VALIDATION_FAILED"`,
		"var CodeRegistry = map[string]CodeMeta{",
		"Retryable: true",
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("codes.go missing %q", want)
		}
	}
}

func TestRenderGoHTTPDTO_PageInfoStruct(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}
	src := readFile(t, filepath.Join(tmp, "backend/internal/shared/types/http_dto.go"))
	must := []string{
		"package types",
		"DefaultPageSize = 20",
		"MaxPageSize     = 100",
		"IdempotencyKeyTTLSeconds = 86400",
		"type PageInfo struct",
		"NextCursor *string",
		"PageSize   int",
		"HasMore    bool",
		`json:"nextCursor"`,
		`json:"pageSize"`,
		`json:"hasMore"`,
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("http_dto.go missing %q", want)
		}
	}
}

func TestRenderGoIdx_Constants(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}
	src := readFile(t, filepath.Join(tmp, "backend/internal/shared/idx/generated.go"))
	must := []string{
		"package idx",
		`const TmpIDPrefix = "tmp_"`,
		`const SampleUUIDv7 = "0195f2d0-`,
		"const UUIDv7RegexExpr",
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("idx/generated.go missing %q", want)
		}
	}
}

func TestRenderTSEnums_UnionTypes(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}
	src := readFile(t, filepath.Join(tmp, "frontend/src/lib/conventions/enums.ts"))
	must := []string{
		"// Code generated by",
		"export type PracticeMode =",
		"| 'core_interview'",
		"| 'debrief_replay';",
		"export const ALL_PRACTICE_MODES: readonly PracticeMode[] = [",
		"export type JobStatus =",
		"| 'dead';",
		"export const ALL_JOB_STATUSES: readonly JobStatus[] = [",
		"export type PrivacyRequestStatus =",
		"export const ALL_SESSION_STATUSES: readonly SessionStatus[] = [",
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("enums.ts missing %q", want)
		}
	}
}

func TestRenderTSErrors_RegistryShape(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}
	src := readFile(t, filepath.Join(tmp, "frontend/src/lib/conventions/errors.ts"))
	must := []string{
		"export const ERROR_CODES = {",
		"AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',",
		"RATE_LIMITED: 'RATE_LIMITED',",
		"export type ErrorCode",
		"export const ERROR_REGISTRY",
		"retryable: true",
		"export interface ApiError {",
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("errors.ts missing %q", want)
		}
	}
}

func TestRenderTSPagination_Defaults(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}
	src := readFile(t, filepath.Join(tmp, "frontend/src/lib/conventions/pagination.ts"))
	must := []string{
		"export const PAGE_SIZE_DEFAULT = 20;",
		"export const PAGE_SIZE_MAX = 100;",
		"export const IDEMPOTENCY_KEY_TTL_SECONDS = 86400;",
		"export interface PageInfo {",
		"nextCursor: string | null;",
		"pageSize: number;",
		"hasMore: boolean;",
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("pagination.ts missing %q", want)
		}
	}
}

func TestRenderTSIds_Constants(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}
	src := readFile(t, filepath.Join(tmp, "frontend/src/lib/ids/generated.ts"))
	must := []string{
		"export const TMP_ID_PREFIX = 'tmp_';",
		"export const SAMPLE_UUID_V7 = '0195f2d0-",
		"export const UUID_V7_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-7",
	}
	for _, want := range must {
		if !strings.Contains(src, want) {
			t.Errorf("ids/generated.ts missing %q", want)
		}
	}
}

func TestRenderAIVocabulary_OutputsDedicatedFiles(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}

	goSrc := readFile(t, filepath.Join(tmp, "backend/internal/shared/ai/vocabulary.go"))
	tsSrc := readFile(t, filepath.Join(tmp, "frontend/src/lib/conventions/ai.ts"))
	errorSrc := readFile(t, filepath.Join(tmp, "frontend/src/lib/conventions/errors.ts"))

	mustGo := []string{
		"package ai",
		`FieldModelProfileName`,
		`"model_profile_name"`,
		`FieldValidationStatus`,
		`"validation_status"`,
		"var AllFieldNames = []FieldName{",
	}
	for _, want := range mustGo {
		if !strings.Contains(goSrc, want) {
			t.Errorf("vocabulary.go missing %q", want)
		}
	}

	mustTS := []string{
		"export const AI_VOCABULARY_FIELDS = {",
		"MODEL_PROFILE_NAME: 'model_profile_name',",
		"VALIDATION_STATUS: 'validation_status',",
		"export type AIVocabularyField",
	}
	for _, want := range mustTS {
		if !strings.Contains(tsSrc, want) {
			t.Errorf("ai.ts missing %q", want)
		}
	}

	for _, forbidden := range []string{"model_profile_name", "validation_status"} {
		if strings.Contains(errorSrc, forbidden) {
			t.Errorf("errors.ts must not contain AI vocabulary field %q", forbidden)
		}
	}
}

func TestRenderAIVocabulary_IncludesOwnerBoundaryComments(t *testing.T) {
	tmp := t.TempDir()
	if err := RunFromBytes(loadYAML(t), tmp, false); err != nil {
		t.Fatalf("Run: %v", err)
	}

	combined := readFile(t, filepath.Join(tmp, "backend/internal/shared/ai/vocabulary.go")) +
		readFile(t, filepath.Join(tmp, "frontend/src/lib/conventions/ai.ts"))

	must := []string{
		"B1 owns field names and validation helpers",
		"A3 owns AIClient, AICallMeta runtime fill, Model Profile schema, and provider adapters",
		"A4 owns AI_GATEWAY_* connection parameter validation",
		"B4 owns typed database columns",
		"F1 owns metrics and log consumption",
	}
	for _, want := range must {
		if !strings.Contains(combined, want) {
			t.Errorf("AI vocabulary generated files missing owner boundary %q", want)
		}
	}
}

func TestPascalSuffix(t *testing.T) {
	cases := map[string]string{
		"core_interview":     "CoreInterview",
		"waiting_user_input": "WaitingUserInput",
		"hr":                 "Hr",
		"basically_ready":    "BasicallyReady",
	}
	for in, want := range cases {
		if got := pascalSuffix(in); got != want {
			t.Errorf("pascalSuffix(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestUpperSnakeFromPascal(t *testing.T) {
	cases := map[string]string{
		"PracticeMode":         "PRACTICE_MODE",
		"SessionStatus":        "SESSION_STATUS",
		"JobStatus":            "JOB_STATUS",
		"PrivacyRequestType":   "PRIVACY_REQUEST_TYPE",
		"PrivacyRequestStatus": "PRIVACY_REQUEST_STATUS",
	}
	for in, want := range cases {
		if got := upperSnakeFromPascal(in); got != want {
			t.Errorf("upperSnakeFromPascal(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestErrorPascal(t *testing.T) {
	cases := map[string]string{
		"AUTH_UNAUTHORIZED":         "AuthUnauthorized",
		"PRACTICE_SESSION_CONFLICT": "PracticeSessionConflict",
		"RATE_LIMITED":              "RateLimited",
		"VALIDATION_FAILED":         "ValidationFailed",
	}
	for in, want := range cases {
		if got := errorPascal(in); got != want {
			t.Errorf("errorPascal(%q) = %q, want %q", in, got, want)
		}
	}
}

// readAllGenerated returns the contents of every file written by Run, keyed by
// its path relative to the repo root.
func readAllGenerated(t *testing.T, root string) map[string][]byte {
	t.Helper()
	out := map[string][]byte{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(root, path)
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		out[rel] = data
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
	return out
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
