package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.\n// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.\n\n"
const generatedTSHeader = "// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.\n// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.\n\n"

// Spec mirrors shared/conventions.yaml; the generator unmarshals this struct via yaml.v3.
type Spec struct {
	Version       float64 `yaml:"version"`
	SchemaVersion int     `yaml:"schemaVersion"`
	SampleUUIDV7  string  `yaml:"sampleUuidV7"`
	UUIDV7Regex   string  `yaml:"uuidV7Regex"`
	TmpIDPrefix   string  `yaml:"tmpIdPrefix"`
	Pagination    struct {
		DefaultPageSize int `yaml:"defaultPageSize"`
		MaxPageSize     int `yaml:"maxPageSize"`
	} `yaml:"pagination"`
	Idempotency struct {
		TTLSeconds int `yaml:"ttlSeconds"`
	} `yaml:"idempotency"`
	Errors       []ErrorSpec       `yaml:"errors"`
	JobStatuses  []string          `yaml:"jobStatuses"`
	Enums        []EnumSpec        `yaml:"enums"`
	Structures   map[string]Struct `yaml:"structures"`
	AIVocabulary struct {
		Capabilities           []string      `yaml:"capabilities"`
		ProviderRegistryFields []AIFieldSpec `yaml:"providerRegistryFields"`
		ModelProfileFields     []AIFieldSpec `yaml:"modelProfileFields"`
		Fields                 []AIFieldSpec `yaml:"fields"`
	} `yaml:"aiVocabulary"`
}

type ErrorSpec struct {
	Code      string `yaml:"code"`
	Message   string `yaml:"message"`
	Retryable bool   `yaml:"retryable"`
}

type EnumSpec struct {
	Name          string   `yaml:"name"`
	SourceSection string   `yaml:"sourceSection"`
	JSONField     string   `yaml:"jsonField"`
	Values        []string `yaml:"values"`
}

type Struct struct {
	Fields []Field `yaml:"fields"`
}

type Field struct {
	Name     string `yaml:"name"`
	Type     string `yaml:"type"`
	Optional bool   `yaml:"optional"`
	Nullable bool   `yaml:"nullable"`
}

type AIFieldSpec struct {
	Name string `yaml:"name"`
}

// Run loads the YAML at yamlPath and renders all generated files under repoRoot.
func Run(yamlPath, repoRoot string, verbose bool) error {
	data, err := os.ReadFile(yamlPath)
	if err != nil {
		return fmt.Errorf("read yaml: %w", err)
	}
	return RunFromBytes(data, repoRoot, verbose)
}

// RunFromBytes is the testable entry point that takes already-loaded YAML bytes.
func RunFromBytes(data []byte, repoRoot string, verbose bool) error {
	var spec Spec
	if err := yaml.Unmarshal(data, &spec); err != nil {
		return fmt.Errorf("parse yaml: %w", err)
	}

	targets := []struct {
		path   string
		render func(*Spec) ([]byte, error)
	}{
		{filepath.Join(repoRoot, "backend/internal/shared/types/enums.go"), renderGoEnums},
		{filepath.Join(repoRoot, "backend/internal/shared/types/http_dto.go"), renderGoHTTPDTO},
		{filepath.Join(repoRoot, "backend/internal/shared/errors/codes.go"), renderGoErrorCodes},
		{filepath.Join(repoRoot, "backend/internal/shared/idx/generated.go"), renderGoIdx},
		{filepath.Join(repoRoot, "backend/internal/shared/ai/vocabulary.go"), renderGoAIVocabulary},
		{filepath.Join(repoRoot, "frontend/src/lib/conventions/enums.ts"), renderTSEnums},
		{filepath.Join(repoRoot, "frontend/src/lib/conventions/errors.ts"), renderTSErrors},
		{filepath.Join(repoRoot, "frontend/src/lib/conventions/ai.ts"), renderTSAIVocabulary},
		{filepath.Join(repoRoot, "frontend/src/lib/conventions/pagination.ts"), renderTSPagination},
		{filepath.Join(repoRoot, "frontend/src/lib/ids/generated.ts"), renderTSIds},
	}

	for _, t := range targets {
		content, err := t.render(&spec)
		if err != nil {
			return fmt.Errorf("render %s: %w", t.path, err)
		}
		if err := writeIfChanged(t.path, content); err != nil {
			return fmt.Errorf("write %s: %w", t.path, err)
		}
		if verbose {
			fmt.Fprintf(os.Stderr, "rendered %s (%d bytes)\n", t.path, len(content))
		}
	}
	return nil
}

func writeIfChanged(path string, content []byte) error {
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, content) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

// pascalSuffix turns a lower_snake_case enum value into a PascalCase suffix
// suitable for Go const naming, e.g. "retry_current_round" -> "RetryCurrentRound".
func pascalSuffix(value string) string {
	parts := strings.Split(value, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// upperSnakeFromPascal turns a PascalCase identifier into UPPER_SNAKE_CASE,
// e.g. "PracticeMode" → "PRACTICE_MODE".
func upperSnakeFromPascal(name string) string {
	var b strings.Builder
	for i, r := range name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'a' && r <= 'z' {
			b.WriteRune(r - 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// goPlural returns the English plural of a Go identifier, handling the common
// "ends in s/x/z" case so that `Status` → `Statuses`, not `Statuss`.
func goPlural(name string) string {
	if strings.HasSuffix(name, "s") || strings.HasSuffix(name, "x") || strings.HasSuffix(name, "z") {
		return name + "es"
	}
	return name + "s"
}

// errorPascal turns an UPPER_SNAKE_CASE error code into a PascalCase Go identifier
// suitable for the "Code" prefix, e.g. "AUTH_UNAUTHORIZED" → "AuthUnauthorized".
func errorPascal(code string) string {
	parts := strings.Split(code, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return strings.Join(parts, "")
}

func fieldPascal(name string) string {
	return pascalSuffix(name)
}

// allEnums returns the §5 enums plus a synthetic JobStatus enum from §4.2.
func allEnums(s *Spec) []EnumSpec {
	out := make([]EnumSpec, 0, len(s.Enums)+1)
	out = append(out, s.Enums...)
	out = append(out, EnumSpec{
		Name:          "JobStatus",
		SourceSection: "4.2",
		JSONField:     "status",
		Values:        s.JobStatuses,
	})
	return out
}

// ----------------------------------------------------------------------------
// Go renderers
// ----------------------------------------------------------------------------

func renderGoEnums(s *Spec) ([]byte, error) {
	type constEntry struct {
		ConstName string
		Value     string
	}
	type enumView struct {
		Name      string
		Section   string
		JSONField string
		Consts    []constEntry
	}

	enums := allEnums(s)
	views := make([]enumView, 0, len(enums))
	for _, e := range enums {
		view := enumView{
			Name:      e.Name,
			Section:   e.SourceSection,
			JSONField: e.JSONField,
		}
		for _, v := range e.Values {
			view.Consts = append(view.Consts, constEntry{
				ConstName: e.Name + pascalSuffix(v),
				Value:     v,
			})
		}
		views = append(views, view)
	}

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package types\n\n")

	for _, v := range views {
		fmt.Fprintf(&buf, "// %s mirrors shared/conventions.yaml sourceSection %s (jsonField: %q).\n", v.Name, v.Section, v.JSONField)
		fmt.Fprintf(&buf, "type %s string\n\n", v.Name)
		fmt.Fprintf(&buf, "const (\n")
		for _, c := range v.Consts {
			fmt.Fprintf(&buf, "\t%s %s = %q\n", c.ConstName, v.Name, c.Value)
		}
		fmt.Fprintf(&buf, ")\n\n")
		fmt.Fprintf(&buf, "// All%s lists every defined value in declaration order.\n", goPlural(v.Name))
		fmt.Fprintf(&buf, "var All%s = []%s{\n", goPlural(v.Name), v.Name)
		for _, c := range v.Consts {
			fmt.Fprintf(&buf, "\t%s,\n", c.ConstName)
		}
		fmt.Fprintf(&buf, "}\n\n")
	}

	return formatGo(buf.Bytes())
}

func renderGoHTTPDTO(s *Spec) ([]byte, error) {
	page, ok := s.Structures["PageInfo"]
	if !ok {
		return nil, fmt.Errorf("structures.PageInfo missing")
	}

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package types\n\n")
	buf.WriteString("// Cursor pagination defaults from shared/conventions.yaml.\n")
	fmt.Fprintf(&buf, "const (\n\tDefaultPageSize = %d\n\tMaxPageSize     = %d\n)\n\n", s.Pagination.DefaultPageSize, s.Pagination.MaxPageSize)
	buf.WriteString("// IdempotencyKeyTTLSeconds is the B1-documented 24h TTL.\n")
	fmt.Fprintf(&buf, "const IdempotencyKeyTTLSeconds = %d\n\n", s.Idempotency.TTLSeconds)

	buf.WriteString("// PageInfo is the B1 cursor pagination wire shape.\n")
	buf.WriteString("type PageInfo struct {\n")
	for _, f := range page.Fields {
		goName := strings.ToUpper(f.Name[:1]) + f.Name[1:]
		goType := goTypeFor(f)
		fmt.Fprintf(&buf, "\t%s %s `json:%q`\n", goName, goType, f.Name)
	}
	buf.WriteString("}\n")

	return formatGo(buf.Bytes())
}

func goTypeFor(f Field) string {
	var base string
	switch f.Type {
	case "string":
		base = "string"
	case "int":
		base = "int"
	case "bool":
		base = "bool"
	case "object":
		base = "map[string]any"
	default:
		base = f.Type
	}
	if f.Nullable {
		return "*" + base
	}
	return base
}

func renderGoErrorCodes(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package errors\n\n")
	buf.WriteString("// Documented error codes from shared/conventions.yaml. All values are\n")
	buf.WriteString("// UPPER_SNAKE_CASE per shared-conventions-codified D-5.\n")
	buf.WriteString("const (\n")
	for _, e := range s.Errors {
		fmt.Fprintf(&buf, "\tCode%s = %q\n", errorPascal(e.Code), e.Code)
	}
	buf.WriteString(")\n\n")

	buf.WriteString("// AllCodes lists every documented error code in declaration order.\n")
	buf.WriteString("var AllCodes = []string{\n")
	for _, e := range s.Errors {
		fmt.Fprintf(&buf, "\tCode%s,\n", errorPascal(e.Code))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// CodeMeta holds the documented default message and retryable hint per error code.\n")
	buf.WriteString("type CodeMeta struct {\n")
	buf.WriteString("\tMessage   string\n")
	buf.WriteString("\tRetryable bool\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// CodeRegistry maps every documented error code to its metadata.\n")
	buf.WriteString("var CodeRegistry = map[string]CodeMeta{\n")
	for _, e := range s.Errors {
		fmt.Fprintf(&buf, "\tCode%s: {Message: %q, Retryable: %t},\n", errorPascal(e.Code), e.Message, e.Retryable)
	}
	buf.WriteString("}\n")

	return formatGo(buf.Bytes())
}

func renderGoIdx(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package idx\n\n")
	buf.WriteString("// TmpIDPrefix is the browser-only temporary id prefix; RequireServerID rejects it.\n")
	fmt.Fprintf(&buf, "const TmpIDPrefix = %q\n\n", s.TmpIDPrefix)
	buf.WriteString("// SampleUUIDv7 is the canonical UUIDv7 used in cross-language fixtures.\n")
	fmt.Fprintf(&buf, "const SampleUUIDv7 = %q\n\n", s.SampleUUIDV7)
	buf.WriteString("// UUIDv7RegexExpr is the regex (string form) used by both Go and TS validators.\n")
	fmt.Fprintf(&buf, "const UUIDv7RegexExpr = %q\n\n", s.UUIDV7Regex)
	buf.WriteString("// IdempotencyKeyTTLSeconds mirrors the B1 24h TTL.\n")
	fmt.Fprintf(&buf, "const IdempotencyKeyTTLSeconds = %d\n", s.Idempotency.TTLSeconds)

	return formatGo(buf.Bytes())
}

func renderGoAIVocabulary(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package ai\n\n")
	buf.WriteString("// Owner boundary:\n")
	buf.WriteString("// B1 owns field names and validation helpers.\n")
	buf.WriteString("// A3 owns AIClient, AICallMeta runtime fill, Model Profile schema, and provider adapters.\n")
	buf.WriteString("// A4 owns AI_PROVIDER_* connection parameter validation.\n")
	buf.WriteString("// B4 owns typed database columns.\n")
	buf.WriteString("// F1 owns metrics and log consumption.\n\n")
	buf.WriteString("// Capability is a B1-owned AI capability literal.\n")
	buf.WriteString("type Capability string\n\n")
	buf.WriteString("const (\n")
	for _, capability := range s.AIVocabulary.Capabilities {
		fmt.Fprintf(&buf, "\tCapability%s Capability = %q\n", pascalSuffix(capability), capability)
	}
	buf.WriteString(")\n\n")

	buf.WriteString("// AllCapabilities lists every AI capability in declaration order.\n")
	buf.WriteString("var AllCapabilities = []Capability{\n")
	for _, capability := range s.AIVocabulary.Capabilities {
		fmt.Fprintf(&buf, "\tCapability%s,\n", pascalSuffix(capability))
	}
	buf.WriteString("}\n\n")
	buf.WriteString("// IsCapability reports whether value is a documented AI capability.\n")
	buf.WriteString("func IsCapability(value string) bool {\n")
	buf.WriteString("\tfor _, capability := range AllCapabilities {\n")
	buf.WriteString("\t\tif string(capability) == value {\n")
	buf.WriteString("\t\t\treturn true\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn false\n")
	buf.WriteString("}\n\n")

	renderGoAIFieldNameType(&buf, "ProviderRegistryFieldName", "provider registry field", s.AIVocabulary.ProviderRegistryFields)
	renderGoAIFieldNameType(&buf, "ModelProfileFieldName", "model profile field", s.AIVocabulary.ModelProfileFields)

	buf.WriteString("// FieldName is a B1-owned AI metadata wire field name.\n")
	buf.WriteString("type FieldName string\n\n")
	buf.WriteString("const (\n")
	for _, field := range s.AIVocabulary.Fields {
		fmt.Fprintf(&buf, "\tField%s FieldName = %q\n", fieldPascal(field.Name), field.Name)
	}
	buf.WriteString(")\n\n")

	buf.WriteString("// AllFieldNames lists every AI metadata field in declaration order.\n")
	buf.WriteString("var AllFieldNames = []FieldName{\n")
	for _, field := range s.AIVocabulary.Fields {
		fmt.Fprintf(&buf, "\tField%s,\n", fieldPascal(field.Name))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// IsFieldName reports whether value is a documented AI metadata field name.\n")
	buf.WriteString("func IsFieldName(value string) bool {\n")
	buf.WriteString("\tfor _, field := range AllFieldNames {\n")
	buf.WriteString("\t\tif string(field) == value {\n")
	buf.WriteString("\t\t\treturn true\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn false\n")
	buf.WriteString("}\n")

	return formatGo(buf.Bytes())
}

func renderGoAIFieldNameType(buf *bytes.Buffer, typeName, label string, fields []AIFieldSpec) {
	fmt.Fprintf(buf, "// %s is a B1-owned AI %s wire field name.\n", typeName, label)
	fmt.Fprintf(buf, "type %s string\n\n", typeName)
	buf.WriteString("const (\n")
	for _, field := range fields {
		fmt.Fprintf(buf, "\t%s%s %s = %q\n", typeName, fieldPascal(field.Name), typeName, field.Name)
	}
	buf.WriteString(")\n\n")

	fmt.Fprintf(buf, "// All%ss lists every AI %s in declaration order.\n", typeName, label)
	fmt.Fprintf(buf, "var All%ss = []%s{\n", typeName, typeName)
	for _, field := range fields {
		fmt.Fprintf(buf, "\t%s%s,\n", typeName, fieldPascal(field.Name))
	}
	buf.WriteString("}\n\n")

	fmt.Fprintf(buf, "// Is%s reports whether value is a documented AI %s.\n", typeName, label)
	fmt.Fprintf(buf, "func Is%s(value string) bool {\n", typeName)
	fmt.Fprintf(buf, "\tfor _, field := range All%ss {\n", typeName)
	buf.WriteString("\t\tif string(field) == value {\n")
	buf.WriteString("\t\t\treturn true\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn false\n")
	buf.WriteString("}\n\n")
}

func formatGo(src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\n--- source ---\n%s", err, src)
	}
	return formatted, nil
}

// ----------------------------------------------------------------------------
// TypeScript renderers
// ----------------------------------------------------------------------------

func renderTSEnums(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)

	enums := allEnums(s)
	for i, e := range enums {
		if i > 0 {
			buf.WriteString("\n")
		}
		fmt.Fprintf(&buf, "// %s mirrors shared/conventions.yaml sourceSection %s (jsonField: %q).\n", e.Name, e.SourceSection, e.JSONField)
		fmt.Fprintf(&buf, "export type %s =\n", e.Name)
		for j, v := range e.Values {
			sep := "|"
			fmt.Fprintf(&buf, "  %s '%s'", sep, v)
			if j == len(e.Values)-1 {
				buf.WriteString(";\n")
			} else {
				buf.WriteString("\n")
			}
		}
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "export const ALL_%s: readonly %s[] = [\n", upperSnakeFromPascal(goPlural(e.Name)), e.Name)
		for _, v := range e.Values {
			fmt.Fprintf(&buf, "  '%s',\n", v)
		}
		buf.WriteString("] as const;\n")
	}

	return buf.Bytes(), nil
}

func renderTSErrors(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	buf.WriteString("// Documented error codes from shared/conventions.yaml. All values are\n")
	buf.WriteString("// UPPER_SNAKE_CASE per shared-conventions-codified D-5.\n\n")

	buf.WriteString("export const ERROR_CODES = {\n")
	for _, e := range s.Errors {
		fmt.Fprintf(&buf, "  %s: '%s',\n", e.Code, e.Code)
	}
	buf.WriteString("} as const;\n\n")

	buf.WriteString("export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];\n\n")

	buf.WriteString("export const ALL_ERROR_CODES: readonly ErrorCode[] = [\n")
	for _, e := range s.Errors {
		fmt.Fprintf(&buf, "  ERROR_CODES.%s,\n", e.Code)
	}
	buf.WriteString("] as const;\n\n")

	buf.WriteString("export interface ErrorMeta {\n")
	buf.WriteString("  message: string;\n")
	buf.WriteString("  retryable: boolean;\n")
	buf.WriteString("}\n\n")

	buf.WriteString("export const ERROR_REGISTRY: Readonly<Record<ErrorCode, ErrorMeta>> = {\n")
	for _, e := range s.Errors {
		retry := "false"
		if e.Retryable {
			retry = "true"
		}
		fmt.Fprintf(&buf, "  %s: { message: '%s', retryable: %s },\n", e.Code, escapeTSString(e.Message), retry)
	}
	buf.WriteString("};\n\n")

	buf.WriteString("export interface ApiError {\n")
	buf.WriteString("  code: string;\n")
	buf.WriteString("  message: string;\n")
	buf.WriteString("  requestId: string;\n")
	buf.WriteString("  retryable: boolean;\n")
	buf.WriteString("  details?: Record<string, unknown>;\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func renderTSAIVocabulary(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	buf.WriteString("// Owner boundary:\n")
	buf.WriteString("// B1 owns field names and validation helpers.\n")
	buf.WriteString("// A3 owns AIClient, AICallMeta runtime fill, Model Profile schema, and provider adapters.\n")
	buf.WriteString("// A4 owns AI_PROVIDER_* connection parameter validation.\n")
	buf.WriteString("// B4 owns typed database columns.\n")
	buf.WriteString("// F1 owns metrics and log consumption.\n\n")
	buf.WriteString("// AI capability literals and wire field names owned by shared-conventions-codified.\n\n")

	buf.WriteString("export const AI_CAPABILITIES = {\n")
	for _, capability := range s.AIVocabulary.Capabilities {
		fmt.Fprintf(&buf, "  %s: '%s',\n", upperSnakeFromPascal(pascalSuffix(capability)), capability)
	}
	buf.WriteString("} as const;\n\n")
	buf.WriteString("export type AICapability = (typeof AI_CAPABILITIES)[keyof typeof AI_CAPABILITIES];\n\n")
	buf.WriteString("export const ALL_AI_CAPABILITIES: readonly AICapability[] = [\n")
	for _, capability := range s.AIVocabulary.Capabilities {
		fmt.Fprintf(&buf, "  AI_CAPABILITIES.%s,\n", upperSnakeFromPascal(pascalSuffix(capability)))
	}
	buf.WriteString("] as const;\n\n")
	buf.WriteString("export function isAICapability(value: string): value is AICapability {\n")
	buf.WriteString("  return (ALL_AI_CAPABILITIES as readonly string[]).includes(value);\n")
	buf.WriteString("}\n\n")

	renderTSAIFieldNameGroup(&buf, "AI_PROVIDER_REGISTRY_FIELDS", "AIProviderRegistryField", "ALL_AI_PROVIDER_REGISTRY_FIELDS", "isAIProviderRegistryField", s.AIVocabulary.ProviderRegistryFields)
	renderTSAIFieldNameGroup(&buf, "AI_MODEL_PROFILE_FIELDS", "AIModelProfileField", "ALL_AI_MODEL_PROFILE_FIELDS", "isAIModelProfileField", s.AIVocabulary.ModelProfileFields)

	buf.WriteString("export const AI_VOCABULARY_FIELDS = {\n")
	for _, field := range s.AIVocabulary.Fields {
		fmt.Fprintf(&buf, "  %s: '%s',\n", upperSnakeFromPascal(fieldPascal(field.Name)), field.Name)
	}
	buf.WriteString("} as const;\n\n")

	buf.WriteString("export type AIVocabularyField = (typeof AI_VOCABULARY_FIELDS)[keyof typeof AI_VOCABULARY_FIELDS];\n\n")

	buf.WriteString("export const ALL_AI_VOCABULARY_FIELDS: readonly AIVocabularyField[] = [\n")
	for _, field := range s.AIVocabulary.Fields {
		fmt.Fprintf(&buf, "  AI_VOCABULARY_FIELDS.%s,\n", upperSnakeFromPascal(fieldPascal(field.Name)))
	}
	buf.WriteString("] as const;\n\n")

	buf.WriteString("export function isAIVocabularyField(value: string): value is AIVocabularyField {\n")
	buf.WriteString("  return (ALL_AI_VOCABULARY_FIELDS as readonly string[]).includes(value);\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func renderTSAIFieldNameGroup(buf *bytes.Buffer, constName, typeName, allName, guardName string, fields []AIFieldSpec) {
	fmt.Fprintf(buf, "export const %s = {\n", constName)
	for _, field := range fields {
		fmt.Fprintf(buf, "  %s: '%s',\n", upperSnakeFromPascal(fieldPascal(field.Name)), field.Name)
	}
	buf.WriteString("} as const;\n\n")
	fmt.Fprintf(buf, "export type %s = (typeof %s)[keyof typeof %s];\n\n", typeName, constName, constName)
	fmt.Fprintf(buf, "export const %s: readonly %s[] = [\n", allName, typeName)
	for _, field := range fields {
		fmt.Fprintf(buf, "  %s.%s,\n", constName, upperSnakeFromPascal(fieldPascal(field.Name)))
	}
	buf.WriteString("] as const;\n\n")
	fmt.Fprintf(buf, "export function %s(value: string): value is %s {\n", guardName, typeName)
	fmt.Fprintf(buf, "  return (%s as readonly string[]).includes(value);\n", allName)
	buf.WriteString("}\n\n")
}

func renderTSPagination(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	buf.WriteString("// Cursor pagination defaults from shared/conventions.yaml.\n")
	fmt.Fprintf(&buf, "export const PAGE_SIZE_DEFAULT = %d;\n", s.Pagination.DefaultPageSize)
	fmt.Fprintf(&buf, "export const PAGE_SIZE_MAX = %d;\n\n", s.Pagination.MaxPageSize)
	buf.WriteString("// IDEMPOTENCY_KEY_TTL_SECONDS is the B1-documented 24h TTL.\n")
	fmt.Fprintf(&buf, "export const IDEMPOTENCY_KEY_TTL_SECONDS = %d;\n\n", s.Idempotency.TTLSeconds)

	buf.WriteString("// PageInfo is the B1 cursor pagination wire shape.\n")
	buf.WriteString("export interface PageInfo {\n")
	page, ok := s.Structures["PageInfo"]
	if !ok {
		return nil, fmt.Errorf("structures.PageInfo missing")
	}
	for _, f := range page.Fields {
		buf.WriteString("  ")
		buf.WriteString(f.Name)
		if f.Optional {
			buf.WriteString("?")
		}
		buf.WriteString(": ")
		buf.WriteString(tsTypeFor(f))
		buf.WriteString(";\n")
	}
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func tsTypeFor(f Field) string {
	base := f.Type
	switch base {
	case "string":
		base = "string"
	case "int":
		base = "number"
	case "bool":
		base = "boolean"
	case "object":
		base = "Record<string, unknown>"
	}
	if f.Nullable {
		return base + " | null"
	}
	return base
}

func renderTSIds(s *Spec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	fmt.Fprintf(&buf, "export const TMP_ID_PREFIX = '%s';\n", s.TmpIDPrefix)
	fmt.Fprintf(&buf, "export const SAMPLE_UUID_V7 = '%s';\n\n", s.SampleUUIDV7)
	buf.WriteString("// UUID_V7_REGEX is the canonical UUIDv7 string format used for validation.\n")
	fmt.Fprintf(&buf, "export const UUID_V7_REGEX = /%s/;\n", s.UUIDV7Regex)
	return buf.Bytes(), nil
}

func escapeTSString(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\\", "\\\\"), "'", "\\'")
}
