// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

// Owner boundary:
// B1 owns field names and validation helpers.
// A3 owns AIClient, AICallMeta runtime fill, Model Profile schema, and provider adapters.
// A4 owns AI_PROVIDER_* connection parameter validation.
// B4 owns typed database columns.
// F1 owns metrics and log consumption.

// AI metadata wire field names owned by shared-conventions-codified.

export const AI_VOCABULARY_FIELDS = {
  MODEL_PROFILE_NAME: 'model_profile_name',
  MODEL_PROFILE_VERSION: 'model_profile_version',
  MODEL_FAMILY: 'model_family',
  MODEL_ID: 'model_id',
  FALLBACK_CHAIN: 'fallback_chain',
  ROUTE: 'route',
  VALIDATION_STATUS: 'validation_status',
  OUTPUT_SCHEMA_VERSION: 'output_schema_version',
  PROMPT_VERSION: 'prompt_version',
  RUBRIC_VERSION: 'rubric_version',
  LANGUAGE: 'language',
  FEATURE_FLAG: 'feature_flag',
  DATA_SOURCE_VERSION: 'data_source_version',
} as const;

export type AIVocabularyField = (typeof AI_VOCABULARY_FIELDS)[keyof typeof AI_VOCABULARY_FIELDS];

export const ALL_AI_VOCABULARY_FIELDS: readonly AIVocabularyField[] = [
  AI_VOCABULARY_FIELDS.MODEL_PROFILE_NAME,
  AI_VOCABULARY_FIELDS.MODEL_PROFILE_VERSION,
  AI_VOCABULARY_FIELDS.MODEL_FAMILY,
  AI_VOCABULARY_FIELDS.MODEL_ID,
  AI_VOCABULARY_FIELDS.FALLBACK_CHAIN,
  AI_VOCABULARY_FIELDS.ROUTE,
  AI_VOCABULARY_FIELDS.VALIDATION_STATUS,
  AI_VOCABULARY_FIELDS.OUTPUT_SCHEMA_VERSION,
  AI_VOCABULARY_FIELDS.PROMPT_VERSION,
  AI_VOCABULARY_FIELDS.RUBRIC_VERSION,
  AI_VOCABULARY_FIELDS.LANGUAGE,
  AI_VOCABULARY_FIELDS.FEATURE_FLAG,
  AI_VOCABULARY_FIELDS.DATA_SOURCE_VERSION,
] as const;

export function isAIVocabularyField(value: string): value is AIVocabularyField {
  return (ALL_AI_VOCABULARY_FIELDS as readonly string[]).includes(value);
}
