// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

// TargetJobStatus mirrors 00-shared-conventions §5.1 (jsonField: "status").
export type TargetJobStatus =
  | 'draft'
  | 'preparing'
  | 'applied'
  | 'interviewing'
  | 'offer'
  | 'rejected'
  | 'archived';

export const ALL_TARGET_JOB_STATUSES: readonly TargetJobStatus[] = [
  'draft',
  'preparing',
  'applied',
  'interviewing',
  'offer',
  'rejected',
  'archived',
] as const;

// TargetJobParseStatus mirrors 00-shared-conventions §5.2 (jsonField: "parseStatus").
export type TargetJobParseStatus =
  | 'queued'
  | 'processing'
  | 'ready'
  | 'failed';

export const ALL_TARGET_JOB_PARSE_STATUSES: readonly TargetJobParseStatus[] = [
  'queued',
  'processing',
  'ready',
  'failed',
] as const;

// PracticeMode mirrors 00-shared-conventions §5.3 (jsonField: "mode").
export type PracticeMode =
  | 'assisted'
  | 'strict'
  | 'debrief_replay';

export const ALL_PRACTICE_MODES: readonly PracticeMode[] = [
  'assisted',
  'strict',
  'debrief_replay',
] as const;

// PracticeGoal mirrors 00-shared-conventions §5.4 (jsonField: "goal").
export type PracticeGoal =
  | 'baseline'
  | 'retry_current_round'
  | 'next_round'
  | 'debrief';

export const ALL_PRACTICE_GOALS: readonly PracticeGoal[] = [
  'baseline',
  'retry_current_round',
  'next_round',
  'debrief',
] as const;

// InterviewerRole mirrors 00-shared-conventions §5.5 (jsonField: "interviewerRole").
export type InterviewerRole =
  | 'generalist'
  | 'hr'
  | 'hiring_manager'
  | 'technical_manager'
  | 'peer';

export const ALL_INTERVIEWER_ROLES: readonly InterviewerRole[] = [
  'generalist',
  'hr',
  'hiring_manager',
  'technical_manager',
  'peer',
] as const;

// SessionStatus mirrors 00-shared-conventions §5.6 (jsonField: "sessionStatus").
export type SessionStatus =
  | 'queued'
  | 'running'
  | 'waiting_user_input'
  | 'completing'
  | 'completed'
  | 'failed'
  | 'cancelled';

export const ALL_SESSION_STATUSES: readonly SessionStatus[] = [
  'queued',
  'running',
  'waiting_user_input',
  'completing',
  'completed',
  'failed',
  'cancelled',
] as const;

// ReportStatus mirrors 00-shared-conventions §5.7 (jsonField: "reportStatus").
export type ReportStatus =
  | 'queued'
  | 'generating'
  | 'ready'
  | 'failed';

export const ALL_REPORT_STATUSES: readonly ReportStatus[] = [
  'queued',
  'generating',
  'ready',
  'failed',
] as const;

// ReadinessTier mirrors 00-shared-conventions §5.8 (jsonField: "readinessTier").
export type ReadinessTier =
  | 'not_ready'
  | 'needs_practice'
  | 'basically_ready'
  | 'well_prepared';

export const ALL_READINESS_TIERS: readonly ReadinessTier[] = [
  'not_ready',
  'needs_practice',
  'basically_ready',
  'well_prepared',
] as const;

// DimensionStatus mirrors 00-shared-conventions §5.9 (jsonField: "dimensionStatus").
export type DimensionStatus =
  | 'strong'
  | 'meets_bar'
  | 'needs_work';

export const ALL_DIMENSION_STATUSES: readonly DimensionStatus[] = [
  'strong',
  'meets_bar',
  'needs_work',
] as const;

// Confidence mirrors 00-shared-conventions §5.10 (jsonField: "confidence").
export type Confidence =
  | 'high'
  | 'medium'
  | 'low';

export const ALL_CONFIDENCES: readonly Confidence[] = [
  'high',
  'medium',
  'low',
] as const;

// QuestionReviewStatus mirrors 00-shared-conventions §5.11 (jsonField: "questionReviewStatus").
export type QuestionReviewStatus =
  | 'open'
  | 'queued_for_retry'
  | 'resolved';

export const ALL_QUESTION_REVIEW_STATUSES: readonly QuestionReviewStatus[] = [
  'open',
  'queued_for_retry',
  'resolved',
] as const;

// DebriefStatus mirrors 00-shared-conventions §5.12 (jsonField: "debriefStatus").
export type DebriefStatus =
  | 'draft'
  | 'completed';

export const ALL_DEBRIEF_STATUSES: readonly DebriefStatus[] = [
  'draft',
  'completed',
] as const;

// PrivacyRequestType mirrors 00-shared-conventions §5.13 (jsonField: "privacyRequestType").
export type PrivacyRequestType =
  | 'export'
  | 'delete';

export const ALL_PRIVACY_REQUEST_TYPES: readonly PrivacyRequestType[] = [
  'export',
  'delete',
] as const;

// PrivacyRequestStatus mirrors 00-shared-conventions §5.13 (jsonField: "privacyRequestStatus").
export type PrivacyRequestStatus =
  | 'queued'
  | 'processing'
  | 'completed'
  | 'failed'
  | 'cancelled';

export const ALL_PRIVACY_REQUEST_STATUSES: readonly PrivacyRequestStatus[] = [
  'queued',
  'processing',
  'completed',
  'failed',
  'cancelled',
] as const;

// JobStatus mirrors 00-shared-conventions §4.2 (jsonField: "status").
export type JobStatus =
  | 'queued'
  | 'running'
  | 'succeeded'
  | 'failed'
  | 'cancelled'
  | 'dead';

export const ALL_JOB_STATUSES: readonly JobStatus[] = [
  'queued',
  'running',
  'succeeded',
  'failed',
  'cancelled',
  'dead',
] as const;
