// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

// TargetJobStatus mirrors shared/conventions.yaml sourceSection 5.1 (jsonField: "status").
export type TargetJobStatus =
  | 'draft'
  | 'preparing'
  | 'applied'
  | 'interviewing'
  | 'offer'
  | 'rejected'
  | 'archived';

export const ALL_TARGET_JOB_STATUSES: readonly TargetJobStatus[] = [
  'draft',
  'preparing',
  'applied',
  'interviewing',
  'offer',
  'rejected',
  'archived',
] as const;

// TargetJobParseStatus mirrors shared/conventions.yaml sourceSection 5.2 (jsonField: "parseStatus").
export type TargetJobParseStatus =
  | 'queued'
  | 'processing'
  | 'ready'
  | 'failed';

export const ALL_TARGET_JOB_PARSE_STATUSES: readonly TargetJobParseStatus[] = [
  'queued',
  'processing',
  'ready',
  'failed',
] as const;

// PracticeGoal mirrors shared/conventions.yaml sourceSection 5.4 (jsonField: "goal").
export type PracticeGoal =
  | 'baseline'
  | 'retry_current_round'
  | 'next_round';

export const ALL_PRACTICE_GOALS: readonly PracticeGoal[] = [
  'baseline',
  'retry_current_round',
  'next_round',
] as const;

// InterviewerRole mirrors shared/conventions.yaml sourceSection 5.5 (jsonField: "interviewerRole").
export type InterviewerRole =
  | 'generalist'
  | 'hr'
  | 'hiring_manager'
  | 'technical_manager'
  | 'peer';

export const ALL_INTERVIEWER_ROLES: readonly InterviewerRole[] = [
  'generalist',
  'hr',
  'hiring_manager',
  'technical_manager',
  'peer',
] as const;

// SessionStatus mirrors shared/conventions.yaml sourceSection 5.6 (jsonField: "sessionStatus").
export type SessionStatus =
  | 'queued'
  | 'running'
  | 'waiting_user_input'
  | 'completing'
  | 'completed'
  | 'failed'
  | 'cancelled';

export const ALL_SESSION_STATUSES: readonly SessionStatus[] = [
  'queued',
  'running',
  'waiting_user_input',
  'completing',
  'completed',
  'failed',
  'cancelled',
] as const;

// ReportStatus mirrors shared/conventions.yaml sourceSection 5.7 (jsonField: "reportStatus").
export type ReportStatus =
  | 'queued'
  | 'generating'
  | 'ready'
  | 'failed';

export const ALL_REPORT_STATUSES: readonly ReportStatus[] = [
  'queued',
  'generating',
  'ready',
  'failed',
] as const;

// ReadinessTier mirrors shared/conventions.yaml sourceSection 5.8 (jsonField: "readinessTier").
export type ReadinessTier =
  | 'not_ready'
  | 'needs_practice'
  | 'basically_ready'
  | 'well_prepared';

export const ALL_READINESS_TIERS: readonly ReadinessTier[] = [
  'not_ready',
  'needs_practice',
  'basically_ready',
  'well_prepared',
] as const;

// DimensionStatus mirrors shared/conventions.yaml sourceSection 5.9 (jsonField: "dimensionStatus").
export type DimensionStatus =
  | 'strong'
  | 'meets_bar'
  | 'needs_work';

export const ALL_DIMENSION_STATUSES: readonly DimensionStatus[] = [
  'strong',
  'meets_bar',
  'needs_work',
] as const;

// Confidence mirrors shared/conventions.yaml sourceSection 5.10 (jsonField: "confidence").
export type Confidence =
  | 'high'
  | 'medium'
  | 'low';

export const ALL_CONFIDENCES: readonly Confidence[] = [
  'high',
  'medium',
  'low',
] as const;

// PrivacyRequestType mirrors shared/conventions.yaml sourceSection 5.13 (jsonField: "privacyRequestType").
export type PrivacyRequestType =
  | 'export'
  | 'delete';

export const ALL_PRIVACY_REQUEST_TYPES: readonly PrivacyRequestType[] = [
  'export',
  'delete',
] as const;

// PrivacyRequestStatus mirrors shared/conventions.yaml sourceSection 5.13 (jsonField: "privacyRequestStatus").
export type PrivacyRequestStatus =
  | 'queued'
  | 'processing'
  | 'completed'
  | 'failed'
  | 'cancelled';

export const ALL_PRIVACY_REQUEST_STATUSES: readonly PrivacyRequestStatus[] = [
  'queued',
  'processing',
  'completed',
  'failed',
  'cancelled',
] as const;

// JobStatus mirrors shared/conventions.yaml sourceSection 4.2 (jsonField: "status").
export type JobStatus =
  | 'queued'
  | 'running'
  | 'succeeded'
  | 'failed'
  | 'cancelled'
  | 'dead';

export const ALL_JOB_STATUSES: readonly JobStatus[] = [
  'queued',
  'running',
  'succeeded',
  'failed',
  'cancelled',
  'dead',
] as const;
