// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

// Documented error codes from shared/conventions.yaml. All values are
// UPPER_SNAKE_CASE per shared-conventions-codified D-5.

export const ERROR_CODES = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  TARGET_IMPORT_FAILED: 'TARGET_IMPORT_FAILED',
  TARGET_JOB_NOT_FOUND: 'TARGET_JOB_NOT_FOUND',
  TARGET_INVALID_STATE_TRANSITION: 'TARGET_INVALID_STATE_TRANSITION',
  PRACTICE_SESSION_CONFLICT: 'PRACTICE_SESSION_CONFLICT',
  PRACTICE_PLAN_NOT_FOUND: 'PRACTICE_PLAN_NOT_FOUND',
  PRACTICE_SESSION_NOT_FOUND: 'PRACTICE_SESSION_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_NOT_READY: 'REPORT_NOT_READY',
  REPORT_CONTEXT_TOO_LARGE: 'REPORT_CONTEXT_TOO_LARGE',
  RESUME_EXPORT_NOT_AVAILABLE: 'RESUME_EXPORT_NOT_AVAILABLE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  IDEMPOTENCY_KEY_MISMATCH: 'IDEMPOTENCY_KEY_MISMATCH',
  RATE_LIMITED: 'RATE_LIMITED',
  AI_PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  AI_FALLBACK_EXHAUSTED: 'AI_FALLBACK_EXHAUSTED',
  AI_UNSUPPORTED_CAPABILITY: 'AI_UNSUPPORTED_CAPABILITY',
  AI_PROVIDER_CONFIG_INVALID: 'AI_PROVIDER_CONFIG_INVALID',
  AI_PROVIDER_SECRET_MISSING: 'AI_PROVIDER_SECRET_MISSING',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ALL_ERROR_CODES: readonly ErrorCode[] = [
  ERROR_CODES.AUTH_UNAUTHORIZED,
  ERROR_CODES.TARGET_IMPORT_FAILED,
  ERROR_CODES.TARGET_JOB_NOT_FOUND,
  ERROR_CODES.TARGET_INVALID_STATE_TRANSITION,
  ERROR_CODES.PRACTICE_SESSION_CONFLICT,
  ERROR_CODES.PRACTICE_PLAN_NOT_FOUND,
  ERROR_CODES.PRACTICE_SESSION_NOT_FOUND,
  ERROR_CODES.REPORT_NOT_FOUND,
  ERROR_CODES.REPORT_NOT_READY,
  ERROR_CODES.REPORT_CONTEXT_TOO_LARGE,
  ERROR_CODES.RESUME_EXPORT_NOT_AVAILABLE,
  ERROR_CODES.VALIDATION_FAILED,
  ERROR_CODES.RESOURCE_NOT_FOUND,
  ERROR_CODES.IDEMPOTENCY_KEY_MISMATCH,
  ERROR_CODES.RATE_LIMITED,
  ERROR_CODES.AI_PROVIDER_TIMEOUT,
  ERROR_CODES.AI_OUTPUT_INVALID,
  ERROR_CODES.AI_FALLBACK_EXHAUSTED,
  ERROR_CODES.AI_UNSUPPORTED_CAPABILITY,
  ERROR_CODES.AI_PROVIDER_CONFIG_INVALID,
  ERROR_CODES.AI_PROVIDER_SECRET_MISSING,
] as const;

export interface ErrorMeta {
  message: string;
  retryable: boolean;
}

export const ERROR_REGISTRY: Readonly<Record<ErrorCode, ErrorMeta>> = {
  AUTH_UNAUTHORIZED: { message: 'authentication required or invalid', retryable: false },
  TARGET_IMPORT_FAILED: { message: 'failed to import target job', retryable: true },
  TARGET_JOB_NOT_FOUND: { message: 'target job not found', retryable: false },
  TARGET_INVALID_STATE_TRANSITION: { message: 'target job state transition is not allowed', retryable: false },
  PRACTICE_SESSION_CONFLICT: { message: 'practice session is in conflicting state', retryable: false },
  PRACTICE_PLAN_NOT_FOUND: { message: 'practice plan not found', retryable: false },
  PRACTICE_SESSION_NOT_FOUND: { message: 'practice session not found', retryable: false },
  REPORT_NOT_FOUND: { message: 'feedback report not found or not accessible', retryable: false },
  REPORT_NOT_READY: { message: 'report is not ready yet', retryable: true },
  REPORT_CONTEXT_TOO_LARGE: { message: 'report context exceeds supported generation size', retryable: false },
  RESUME_EXPORT_NOT_AVAILABLE: { message: 'resume version export is not available in P0', retryable: false },
  VALIDATION_FAILED: { message: 'request validation failed', retryable: false },
  RESOURCE_NOT_FOUND: { message: 'requested resource not found or not accessible', retryable: false },
  IDEMPOTENCY_KEY_MISMATCH: { message: 'idempotency key was reused with a different request body', retryable: false },
  RATE_LIMITED: { message: 'rate limit exceeded', retryable: true },
  AI_PROVIDER_TIMEOUT: { message: 'AI provider request timed out', retryable: true },
  AI_OUTPUT_INVALID: { message: 'AI output failed schema validation', retryable: false },
  AI_FALLBACK_EXHAUSTED: { message: 'AI fallback chain exhausted', retryable: true },
  AI_UNSUPPORTED_CAPABILITY: { message: 'AI capability is not supported', retryable: false },
  AI_PROVIDER_CONFIG_INVALID: { message: 'AI provider registry or model profile configuration is invalid', retryable: false },
  AI_PROVIDER_SECRET_MISSING: { message: 'AI provider secret is missing', retryable: false },
};

export interface ApiError {
  code: string;
  message: string;
  requestId: string;
  retryable: boolean;
  details?: Record<string, unknown>;
}
