// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

// Documented error codes from shared/conventions.yaml. All values are
// UPPER_SNAKE_CASE per shared-conventions-codified D-5.

export const ERROR_CODES = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  TARGET_IMPORT_FAILED: 'TARGET_IMPORT_FAILED',
  PRACTICE_SESSION_CONFLICT: 'PRACTICE_SESSION_CONFLICT',
  REPORT_NOT_READY: 'REPORT_NOT_READY',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  AI_PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  AI_FALLBACK_EXHAUSTED: 'AI_FALLBACK_EXHAUSTED',
  AI_UNSUPPORTED_CAPABILITY: 'AI_UNSUPPORTED_CAPABILITY',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ALL_ERROR_CODES: readonly ErrorCode[] = [
  ERROR_CODES.AUTH_UNAUTHORIZED,
  ERROR_CODES.TARGET_IMPORT_FAILED,
  ERROR_CODES.PRACTICE_SESSION_CONFLICT,
  ERROR_CODES.REPORT_NOT_READY,
  ERROR_CODES.VALIDATION_FAILED,
  ERROR_CODES.RATE_LIMITED,
  ERROR_CODES.AI_PROVIDER_TIMEOUT,
  ERROR_CODES.AI_OUTPUT_INVALID,
  ERROR_CODES.AI_FALLBACK_EXHAUSTED,
  ERROR_CODES.AI_UNSUPPORTED_CAPABILITY,
] as const;

export interface ErrorMeta {
  message: string;
  retryable: boolean;
}

export const ERROR_REGISTRY: Readonly<Record<ErrorCode, ErrorMeta>> = {
  AUTH_UNAUTHORIZED: { message: 'authentication required or invalid', retryable: false },
  TARGET_IMPORT_FAILED: { message: 'failed to import target job', retryable: true },
  PRACTICE_SESSION_CONFLICT: { message: 'practice session is in conflicting state', retryable: false },
  REPORT_NOT_READY: { message: 'report is not ready yet', retryable: true },
  VALIDATION_FAILED: { message: 'request validation failed', retryable: false },
  RATE_LIMITED: { message: 'rate limit exceeded', retryable: true },
  AI_PROVIDER_TIMEOUT: { message: 'AI provider request timed out', retryable: true },
  AI_OUTPUT_INVALID: { message: 'AI output failed schema validation', retryable: false },
  AI_FALLBACK_EXHAUSTED: { message: 'AI fallback chain exhausted', retryable: true },
  AI_UNSUPPORTED_CAPABILITY: { message: 'AI capability is not supported', retryable: false },
};

export interface ApiError {
  code: string;
  message: string;
  requestId: string;
  retryable: boolean;
  details?: Record<string, unknown>;
}
