// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

// Cursor pagination defaults (00-shared-conventions §3.3).
export const PAGE_SIZE_DEFAULT = 20;
export const PAGE_SIZE_MAX = 100;

// IDEMPOTENCY_KEY_TTL_SECONDS is the documented 24h TTL (00-shared-conventions §3.4).
export const IDEMPOTENCY_KEY_TTL_SECONDS = 86400;

// PageInfo is the cursor pagination wire shape (00-shared-conventions §3.1).
export interface PageInfo {
  nextCursor: string | null;
  pageSize: number;
  hasMore: boolean;
}
