// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

// Cursor pagination defaults from shared/conventions.yaml.
export const PAGE_SIZE_DEFAULT = 20;
export const PAGE_SIZE_MAX = 100;

// IDEMPOTENCY_KEY_TTL_SECONDS is the B1-documented 24h TTL.
export const IDEMPOTENCY_KEY_TTL_SECONDS = 86400;

// PageInfo is the B1 cursor pagination wire shape.
export interface PageInfo {
  nextCursor: string | null;
  pageSize: number;
  hasMore: boolean;
}
