package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const tsGeneratedHeader = "// Code generated by backend/cmd/codegen/openapi; DO NOT EDIT.\n// Source: openapi/openapi.yaml + shared/conventions.yaml — owned by docs/spec/openapi-v1-contract."

func renderTS(doc *OpenAPI, conv *Conventions, templatesDir, outDir string) error {
	typesData, err := buildTSTypesData(doc, conv)
	if err != nil {
		return err
	}
	if err := renderTSTemplate(filepath.Join(templatesDir, "ts", "types.tmpl"), filepath.Join(outDir, "types.ts"), typesData); err != nil {
		return err
	}

	clientData, err := buildTSClientData(doc)
	if err != nil {
		return err
	}
	if err := renderTSTemplate(filepath.Join(templatesDir, "ts", "client.tmpl"), filepath.Join(outDir, "client.ts"), clientData); err != nil {
		return err
	}

	specYAML := string(doc.Raw)
	literal := tsTemplateStringLiteral(specYAML)
	specData := map[string]any{
		"Header":          tsGeneratedHeader,
		"SpecVersion":     doc.Version,
		"SpecYAMLLiteral": literal,
	}
	return renderTSTemplate(filepath.Join(templatesDir, "ts", "spec.tmpl"), filepath.Join(outDir, "spec.ts"), specData)
}

func renderTSTemplate(templatePath, outPath string, data any) error {
	tmplBytes, err := os.ReadFile(templatePath)
	if err != nil {
		return err
	}
	tmpl, err := template.New(filepath.Base(templatePath)).Parse(string(tmplBytes))
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	return os.WriteFile(outPath, buf.Bytes(), 0o644)
}

// tsTypesData populates types.tmpl.
type tsTypesData struct {
	Header               string
	B1ImportPath         string
	B1ErrorsImportPath   string
	B1ImportedTypes      []string
	B1ImportedErrorCodes []string
	B1Aliases            []tsAliasView
	DomainSchemas        []tsSchemaView
}

type tsAliasView struct {
	TSName   string
	TSTarget string
}

type tsSchemaView struct {
	Kind          string // "enum" | "object" | "alias" | "any"
	TSName        string
	PluralName    string
	TSEnumLiteral string
	TSEnumArray   string
	Fields        []tsFieldView
	TSAliasTarget string
}

type tsFieldView struct {
	JSONName string
	TSType   string
	Optional bool
}

func buildTSTypesData(doc *OpenAPI, conv *Conventions) (*tsTypesData, error) {
	imported := []string{"ApiError", "PageInfo"}
	for _, e := range conv.Enums {
		imported = append(imported, e.Name)
	}
	sort.Strings(imported)

	b1Aliases := []tsAliasView{
		{TSName: "ApiError", TSTarget: "ApiErrorAlias"},
		{TSName: "PageInfo", TSTarget: "PageInfoAlias"},
		{TSName: "ApiErrorCode", TSTarget: tsErrorCodeUnion(conv)},
		{TSName: "JobStatus", TSTarget: tsLiteralUnion(conv.JobStatuses)},
	}
	for _, e := range conv.Enums {
		b1Aliases = append(b1Aliases, tsAliasView{TSName: e.Name, TSTarget: e.Name + "Alias"})
	}

	// Re-import B1 types under aliased names so the re-exports above can rebind.
	importedAliased := []string{"ApiError as ApiErrorAlias", "PageInfo as PageInfoAlias"}
	for _, e := range conv.Enums {
		importedAliased = append(importedAliased, fmt.Sprintf("%s as %sAlias", e.Name, e.Name))
	}
	sort.Strings(importedAliased)

	codeNames := []string{}
	for _, c := range conv.Errors {
		codeNames = append(codeNames, "Code"+camelize(strings.ToLower(c.Code)))
	}
	sort.Strings(codeNames)

	aliasNames := map[string]struct{}{}
	for _, a := range b1Aliases {
		aliasNames[a.TSName] = struct{}{}
	}

	schemaOrder, err := doc.SortedSchemaNames()
	if err != nil {
		return nil, err
	}
	schemas := doc.Schemas()
	domain := []tsSchemaView{}
	for _, name := range schemaOrder {
		if _, isAlias := aliasNames[name]; isAlias {
			continue
		}
		raw, ok := schemas[name].(map[string]any)
		if !ok {
			continue
		}
		view := classifyTSSchema(name, raw)
		domain = append(domain, view)
	}

	return &tsTypesData{
		Header:               tsGeneratedHeader,
		B1ImportPath:         "../../lib/conventions",
		B1ErrorsImportPath:   "../../lib/conventions/errors",
		B1ImportedTypes:      importedAliased,
		B1ImportedErrorCodes: codeNames,
		B1Aliases:            b1Aliases,
		DomainSchemas:        domain,
	}, nil
}

func tsLiteralUnion(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(parts, " | ")
}

func tsErrorCodeUnion(conv *Conventions) string {
	codes := b1OrderedErrorCodes(conv)
	parts := make([]string, len(codes))
	for i, c := range codes {
		parts[i] = fmt.Sprintf("%q", c)
	}
	return strings.Join(parts, " | ")
}

func classifyTSSchema(name string, raw map[string]any) tsSchemaView {
	view := tsSchemaView{TSName: name, PluralName: pluralize(name)}

	if t, _ := raw["type"].(string); t == "string" {
		if vs, ok := raw["enum"].([]any); ok && len(vs) > 0 {
			parts := make([]string, 0, len(vs))
			arrParts := make([]string, 0, len(vs))
			for _, v := range vs {
				if s, ok := v.(string); ok {
					parts = append(parts, fmt.Sprintf("%q", s))
					arrParts = append(arrParts, fmt.Sprintf("%q", s))
				}
			}
			view.Kind = "enum"
			view.TSEnumLiteral = strings.Join(parts, " | ")
			view.TSEnumArray = strings.Join(arrParts, ", ")
			return view
		}
	}

	if al, ok := raw["allOf"].([]any); ok && len(al) > 0 {
		view.Kind = "object"
		view.Fields = []tsFieldView{
			{JSONName: "items", TSType: tsAllOfItemsType(al)},
			{JSONName: "pageInfo", TSType: "PageInfo"},
		}
		return view
	}

	if t, _ := raw["type"].(string); t == "object" {
		view.Kind = "object"
		view.Fields = buildTSObjectFields(raw)
		return view
	}

	if ref, ok := raw["$ref"].(string); ok {
		view.Kind = "alias"
		view.TSAliasTarget = extractRefName(ref)
		return view
	}

	view.Kind = "any"
	return view
}

func tsAllOfItemsType(al []any) string {
	for _, item := range al {
		m, _ := item.(map[string]any)
		props, _ := m["properties"].(map[string]any)
		if itemsProp, ok := props["items"].(map[string]any); ok {
			if arr, ok := itemsProp["items"].(map[string]any); ok {
				if ref, ok := arr["$ref"].(string); ok {
					return extractRefName(ref) + "[]"
				}
			}
		}
	}
	return "unknown[]"
}

func buildTSObjectFields(raw map[string]any) []tsFieldView {
	props, _ := raw["properties"].(map[string]any)
	required := map[string]struct{}{}
	if rs, ok := raw["required"].([]any); ok {
		for _, r := range rs {
			if s, ok := r.(string); ok {
				required[s] = struct{}{}
			}
		}
	}
	names := make([]string, 0, len(props))
	for n := range props {
		names = append(names, n)
	}
	sort.Strings(names)
	out := []tsFieldView{}
	for _, n := range names {
		spec, _ := props[n].(map[string]any)
		ts := tsTypeFor(spec)
		_, req := required[n]
		out = append(out, tsFieldView{JSONName: n, TSType: ts, Optional: !req})
	}
	return out
}

func tsTypeFor(spec map[string]any) string {
	if spec == nil {
		return "unknown"
	}
	if ref, ok := spec["$ref"].(string); ok {
		return extractRefName(ref)
	}
	if oneOf, ok := spec["oneOf"].([]any); ok {
		hasNull := false
		altTypes := []string{}
		for _, alt := range oneOf {
			altMap, _ := alt.(map[string]any)
			if t, _ := altMap["type"].(string); t == "null" {
				hasNull = true
				continue
			}
			altTypes = append(altTypes, tsTypeFor(altMap))
		}
		if hasNull && len(altTypes) > 0 {
			return strings.Join(altTypes, " | ") + " | null"
		}
		if len(altTypes) > 0 {
			return strings.Join(altTypes, " | ")
		}
		return "unknown"
	}
	if al, ok := spec["allOf"].([]any); ok && len(al) == 1 {
		first, _ := al[0].(map[string]any)
		return tsTypeFor(first)
	}
	t, _ := spec["type"].(string)
	switch t {
	case "string":
		if vs, ok := spec["enum"].([]any); ok && len(vs) > 0 {
			parts := []string{}
			for _, v := range vs {
				if s, ok := v.(string); ok {
					parts = append(parts, fmt.Sprintf("%q", s))
				}
			}
			return strings.Join(parts, " | ")
		}
		return "string"
	case "boolean":
		return "boolean"
	case "integer", "number":
		return "number"
	case "array":
		items, _ := spec["items"].(map[string]any)
		return tsTypeFor(items) + "[]"
	case "object":
		if _, has := spec["properties"]; !has {
			return "Record<string, unknown>"
		}
		return "Record<string, unknown>"
	}
	if nullable, _ := spec["nullable"].(bool); nullable {
		return "string | null"
	}
	return "unknown"
}

// tsTemplateStringLiteral produces a JS double-quoted string literal for the
// raw spec YAML, with backslash + quote + newline + carriage return escaped.
func tsTemplateStringLiteral(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			sb.WriteString(`\\`)
		case '"':
			sb.WriteString(`\"`)
		case '\n':
			sb.WriteString(`\n`)
		case '\r':
			sb.WriteString(`\r`)
		case '\t':
			sb.WriteString(`\t`)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

// --- TS client ----------------------------------------------------------------

type tsClientData struct {
	Header     string
	Operations []tsClientOpView
}

type tsClientOpView struct {
	OperationID       string
	Method            string
	MethodUpper       string
	Path              string
	Summary           string
	TSMethodSignature string
	TSReturnType      string
	TSPathExpression  string
	TSBodyArg         string
	TSOptsArg         string
}

func buildTSClientData(doc *OpenAPI) (*tsClientData, error) {
	ops := []tsClientOpView{}
	for _, p := range doc.Paths() {
		for _, verb := range p.Methods() {
			rawOp, _ := p.Item[verb].(map[string]any)
			id, _ := rawOp["operationId"].(string)
			summary, _ := rawOp["summary"].(string)
			pathParams := collectPathParams(p.Path)

			// Build TS method signature args.
			args := []string{}
			pathExprArgs := map[string]string{}
			for _, pp := range pathParams {
				args = append(args, pp.GoName+": string")
				pathExprArgs[pp.Name] = pp.GoName
			}
			hasBody := false
			bodyType := "unknown"
			if rb, ok := rawOp["requestBody"].(map[string]any); ok {
				hasBody = true
				if t := tsRequestBodyType(rb); t != "" {
					bodyType = t
				}
			}
			if hasBody {
				args = append(args, "body: "+bodyType)
			}
			args = append(args, "opts?: RequestOptions")

			view := tsClientOpView{
				OperationID:       id,
				Method:            verb,
				MethodUpper:       strings.ToUpper(verb),
				Path:              p.Path,
				Summary:           summary,
				TSMethodSignature: strings.Join(args, ", "),
				TSReturnType:      tsResponseType(rawOp),
				TSPathExpression:  buildTSPathExpression(p.Path, pathExprArgs),
				TSBodyArg:         tsBodyArg(hasBody),
				TSOptsArg:         "opts",
			}
			ops = append(ops, view)
		}
	}
	sort.Slice(ops, func(i, j int) bool {
		if ops[i].Path != ops[j].Path {
			return ops[i].Path < ops[j].Path
		}
		return ops[i].Method < ops[j].Method
	})
	return &tsClientData{Header: tsGeneratedHeader, Operations: ops}, nil
}

func tsBodyArg(hasBody bool) string {
	if hasBody {
		return "body"
	}
	return "undefined"
}

// buildTSPathExpression returns either a plain quoted string or a template
// literal that interpolates path parameters in encodeURIComponent calls via
// the runtime helper.
func buildTSPathExpression(path string, params map[string]string) string {
	if len(params) == 0 {
		return fmt.Sprintf("%q", path)
	}
	args := make([]string, 0, len(params))
	keys := make([]string, 0, len(params))
	for k := range params {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		args = append(args, fmt.Sprintf("%s: %s", k, params[k]))
	}
	return fmt.Sprintf("buildPath(%q, { %s })", path, strings.Join(args, ", "))
}

func tsRequestBodyType(rb map[string]any) string {
	content, _ := rb["content"].(map[string]any)
	if content == nil {
		return ""
	}
	app, _ := content["application/json"].(map[string]any)
	if app == nil {
		return ""
	}
	schema, _ := app["schema"].(map[string]any)
	return qualifyTSTypeRef(tsTypeFor(schema))
}

func tsResponseType(op map[string]any) string {
	resps, _ := op["responses"].(map[string]any)
	preferred := []string{"200", "201", "202", "204", "501"}
	for _, code := range preferred {
		r, ok := resps[code].(map[string]any)
		if !ok {
			continue
		}
		if code == "204" {
			return "void"
		}
		content, _ := r["content"].(map[string]any)
		app, _ := content["application/json"].(map[string]any)
		schema, _ := app["schema"].(map[string]any)
		if schema == nil {
			continue
		}
		return qualifyTSTypeRef(tsTypeFor(schema))
	}
	return "unknown"
}

// qualifyTSTypeRef rewrites bare type names (e.g., `Foo`, `Foo[]`) to
// `Types.Foo` / `Types.Foo[]`. Primitives, anonymous shapes, and obvious
// containers are passed through unchanged.
func qualifyTSTypeRef(ts string) string {
	switch ts {
	case "", "string", "number", "boolean", "void", "unknown", "null":
		return ts
	}
	if strings.HasPrefix(ts, "Record<") {
		return ts
	}
	suffix := ""
	for strings.HasSuffix(ts, "[]") {
		suffix += "[]"
		ts = strings.TrimSuffix(ts, "[]")
	}
	if strings.Contains(ts, " | ") {
		// Union type — qualify each named identifier.
		parts := strings.Split(ts, " | ")
		for i, p := range parts {
			parts[i] = qualifyTSTypeRef(strings.TrimSpace(p))
		}
		return strings.Join(parts, " | ") + suffix
	}
	if strings.HasPrefix(ts, "\"") {
		return ts + suffix
	}
	if ts == "string" || ts == "number" || ts == "boolean" || ts == "null" || ts == "unknown" {
		return ts + suffix
	}
	return "Types." + ts + suffix
}
