package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const goGeneratedHeader = "// Code generated by backend/cmd/codegen/openapi; DO NOT EDIT.\n// Source: openapi/openapi.yaml + shared/conventions.yaml — owned by docs/spec/openapi-v1-contract."

// renderGo emits types.gen.go, server.gen.go, spec.gen.go and copies
// openapi.yaml into the generated directory so spec.gen.go's `//go:embed`
// resolves a sibling file (Go embed cannot cross package boundaries).
func renderGo(doc *OpenAPI, conv *Conventions, templatesDir, outDir string) error {
	// 1. Copy openapi.yaml into the generated dir for `//go:embed`.
	embedDst := filepath.Join(outDir, "openapi.yaml")
	if err := os.WriteFile(embedDst, doc.Raw, 0o644); err != nil {
		return err
	}

	// 2. types.gen.go
	typesData, err := buildGoTypesData(doc, conv)
	if err != nil {
		return err
	}
	if err := renderGoTemplate(filepath.Join(templatesDir, "go", "types.tmpl"), filepath.Join(outDir, "types.gen.go"), typesData); err != nil {
		return err
	}

	// 3. server.gen.go
	opsData, err := buildGoServerData(doc)
	if err != nil {
		return err
	}
	if err := renderGoTemplate(filepath.Join(templatesDir, "go", "server.tmpl"), filepath.Join(outDir, "server.gen.go"), opsData); err != nil {
		return err
	}

	// 4. spec.gen.go
	specData := map[string]any{
		"Header":      goGeneratedHeader,
		"SpecVersion": doc.Version,
	}
	return renderGoTemplate(filepath.Join(templatesDir, "go", "spec.tmpl"), filepath.Join(outDir, "spec.gen.go"), specData)
}

func renderGoTemplate(templatePath, outPath string, data any) error {
	tmplBytes, err := os.ReadFile(templatePath)
	if err != nil {
		return err
	}
	tmpl, err := template.New(filepath.Base(templatePath)).Funcs(template.FuncMap{
		// Constructed inside builders; templates only consume already-prepared values.
	}).Parse(string(tmplBytes))
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	formatted, ferr := format.Source(buf.Bytes())
	if ferr != nil {
		// On format error, write raw to ease debugging then fail.
		_ = os.WriteFile(outPath, buf.Bytes(), 0o644)
		return fmt.Errorf("gofmt %s: %w", outPath, ferr)
	}
	return os.WriteFile(outPath, formatted, 0o644)
}

// goTypesData populates the types.tmpl template.
type goTypesData struct {
	Header        string
	SharedPkg     string
	ErrorsPkg     string
	B1Aliases     []b1AliasView
	DomainSchemas []goSchemaView
}

type b1AliasView struct {
	Name   string
	Target string
}

type goEnumValueView struct {
	ParentName string
	Value      string
	ConstName  string
}

type goSchemaView struct {
	Kind        string // "enum" | "object" | "alias" | "any"
	Name        string
	PluralName  string
	Comment     string
	EnumValues  []goEnumValueView
	Fields      []goFieldView
	AliasTarget string
}

type goFieldView struct {
	GoName    string
	GoType    string
	JSONName  string
	YAMLTag   string
	OmitEmpty bool
	Comment   string
}

// b1OwnedSchemas lists the openapi schema names whose Go representation is
// an alias to B1-owned shared packages. Each entry is (openapi schema name,
// Go target). ApiError maps to the canonical B1 errors package; PageInfo,
// JobStatus and the B1 enums map to B1 shared types. ApiErrorCode remains
// rendered from OpenAPI because B2 carries OpenAPI-local P0 export exceptions.
func b1OwnedSchemas(conv *Conventions) []b1AliasView {
	out := []b1AliasView{
		{Name: "ApiError", Target: "sharederrors.APIError"},
		{Name: "PageInfo", Target: "sharedtypes.PageInfo"},
		{Name: "JobStatus", Target: "sharedtypes.JobStatus"},
	}
	for _, e := range conv.Enums {
		out = append(out, b1AliasView{
			Name:   e.Name,
			Target: "sharedtypes." + e.Name,
		})
	}
	return out
}

// buildGoTypesData assembles the goTypesData for types.tmpl.
func buildGoTypesData(doc *OpenAPI, conv *Conventions) (*goTypesData, error) {
	aliases := b1OwnedSchemas(conv)
	aliasNames := map[string]struct{}{}
	for _, a := range aliases {
		aliasNames[a.Name] = struct{}{}
	}

	schemaOrder, err := doc.SortedSchemaNames()
	if err != nil {
		return nil, err
	}
	schemas := doc.Schemas()
	domain := []goSchemaView{}
	for _, name := range schemaOrder {
		if _, isAlias := aliasNames[name]; isAlias {
			continue
		}
		raw, ok := schemas[name].(map[string]any)
		if !ok {
			continue
		}
		view, err := classifyGoSchema(name, raw)
		if err != nil {
			return nil, err
		}
		domain = append(domain, view)
	}
	return &goTypesData{
		Header:        goGeneratedHeader,
		SharedPkg:     `sharedtypes "github.com/monshunter/easyinterview/backend/internal/shared/types"`,
		ErrorsPkg:     `sharederrors "github.com/monshunter/easyinterview/backend/internal/shared/errors"`,
		B1Aliases:     aliases,
		DomainSchemas: domain,
	}, nil
}

// classifyGoSchema converts an OpenAPI schema map into a goSchemaView. We
// handle object / string-enum / array / oneOf-nullable / allOf / $ref / primitive
// patterns; everything else collapses to a `any` alias to keep generation
// deterministic.
func classifyGoSchema(name string, raw map[string]any) (goSchemaView, error) {
	view := goSchemaView{Name: name, PluralName: pluralize(name)}

	// String + enum → typed string + const block.
	if t, _ := raw["type"].(string); t == "string" {
		if vs, ok := raw["enum"].([]any); ok && len(vs) > 0 {
			view.Kind = "enum"
			for _, v := range vs {
				if s, ok := v.(string); ok {
					view.EnumValues = append(view.EnumValues, goEnumValueView{
						ParentName: name,
						Value:      s,
						ConstName:  name + camelize(s),
					})
				}
			}
			return view, nil
		}
	}

	// Only the canonical PaginatedEnvelope composition is rendered as a
	// pagination struct. Conditional allOf branches (for example status-based
	// report constraints) refine the object schema and must not replace its
	// declared properties.
	if al, ok := raw["allOf"].([]any); ok && isPaginatedEnvelopeAllOf(al) {
		if v, err := classifyAllOf(name, al); err == nil {
			return v, nil
		}
	}

	// Object → struct.
	if t, _ := raw["type"].(string); t == "object" {
		view.Kind = "object"
		fields, err := buildGoObjectFields(raw)
		if err != nil {
			return view, err
		}
		view.Fields = fields
		return view, nil
	}

	// Pure $ref alias.
	if ref, ok := raw["$ref"].(string); ok {
		view.Kind = "alias"
		view.AliasTarget = goRefName(extractRefName(ref))
		return view, nil
	}

	view.Kind = "any"
	return view, nil
}

func isPaginatedEnvelopeAllOf(al []any) bool {
	for _, item := range al {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		if ref, _ := m["$ref"].(string); extractRefName(ref) == "PaginatedEnvelope" {
			return true
		}
	}
	return false
}

// classifyAllOf handles `allOf: [{$ref: ...PaginatedEnvelope}, {properties: { items: ...}}]`.
func classifyAllOf(name string, al []any) (goSchemaView, error) {
	view := goSchemaView{Name: name, Kind: "object", PluralName: pluralize(name)}
	view.Fields = []goFieldView{
		{GoName: "Items", GoType: "[]any", JSONName: "items"},
		{GoName: "PageInfo", GoType: "PageInfo", JSONName: "pageInfo"},
	}
	for _, item := range al {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		props, ok := m["properties"].(map[string]any)
		if !ok {
			continue
		}
		if itemsProp, ok := props["items"].(map[string]any); ok {
			if arr, ok := itemsProp["items"].(map[string]any); ok {
				if ref, ok := arr["$ref"].(string); ok {
					view.Fields[0].GoType = "[]" + goRefName(extractRefName(ref))
				}
			}
		}
	}
	return view, nil
}

// buildGoObjectFields walks `properties` + `required` to produce field views.
func buildGoObjectFields(raw map[string]any) ([]goFieldView, error) {
	props, _ := raw["properties"].(map[string]any)
	required := map[string]struct{}{}
	if rs, ok := raw["required"].([]any); ok {
		for _, r := range rs {
			if s, ok := r.(string); ok {
				required[s] = struct{}{}
			}
		}
	}
	names := make([]string, 0, len(props))
	for n := range props {
		names = append(names, n)
	}
	sort.Strings(names)
	out := []goFieldView{}
	for _, n := range names {
		spec, _ := props[n].(map[string]any)
		gtype := goTypeFor(spec)
		_, req := required[n]
		field := goFieldView{
			GoName:   exportedGoName(n),
			GoType:   gtype,
			JSONName: n,
		}
		if !req {
			field.OmitEmpty = true
			if !strings.HasPrefix(gtype, "[]") && !strings.HasPrefix(gtype, "map[") && !strings.HasPrefix(gtype, "*") && gtype != "any" {
				field.GoType = "*" + gtype
			}
		}
		out = append(out, field)
	}
	return out, nil
}

// goTypeFor maps an OpenAPI schema fragment to a Go type literal. Best-effort:
// unknown shapes collapse to `any` to keep the generator from crashing on
// schemas it does not yet understand.
func goTypeFor(spec map[string]any) string {
	if spec == nil {
		return "any"
	}
	nullable, _ := spec["nullable"].(bool)
	withNull := func(base string) string {
		if nullable && !strings.HasPrefix(base, "*") {
			return "*" + base
		}
		return base
	}
	if ref, ok := spec["$ref"].(string); ok {
		return withNull(goRefName(extractRefName(ref)))
	}
	if oneOf, ok := spec["oneOf"].([]any); ok {
		// Detect `oneOf: [X, {type: 'null'}]` → `*X`.
		var ref string
		var prim string
		hasNull := false
		for _, alt := range oneOf {
			altMap, _ := alt.(map[string]any)
			if t, _ := altMap["type"].(string); t == "null" {
				hasNull = true
				continue
			}
			if r, _ := altMap["$ref"].(string); r != "" {
				ref = r
			} else {
				prim = goTypeFor(altMap)
			}
		}
		if hasNull && ref != "" {
			return "*" + goRefName(extractRefName(ref))
		}
		if hasNull && prim != "" {
			return "*" + prim
		}
		return "any"
	}
	if al, ok := spec["allOf"].([]any); ok && len(al) == 1 {
		if first, ok := al[0].(map[string]any); ok {
			return goTypeFor(first)
		}
	}
	t, _ := spec["type"].(string)
	switch t {
	case "string":
		return withNull("string")
	case "boolean":
		return withNull("bool")
	case "integer":
		switch f, _ := spec["format"].(string); f {
		case "int64":
			return withNull("int64")
		default:
			return withNull("int32")
		}
	case "number":
		return withNull("float64")
	case "array":
		items, _ := spec["items"].(map[string]any)
		return withNull("[]" + goTypeFor(items))
	case "object":
		// Free-form object → map[string]any unless we have a property tree.
		if _, hasProps := spec["properties"]; !hasProps {
			return withNull("map[string]any")
		}
		return withNull("any")
	}
	return "any"
}

// goRefName resolves a schema name to its Go counterpart inside the
// generated package. B1-aliased names map to the local alias; others are
// referenced by their bare schema name (also a Go identifier).
func goRefName(name string) string {
	if name == "" {
		return "any"
	}
	return name
}

// goServerData populates the server.tmpl template.
type goServerData struct {
	Header     string
	Operations []goOperationView
}

type goOperationView struct {
	OperationID       string
	GoMethodName      string
	Method            string
	MethodUpper       string
	Path              string
	Summary           string
	PathParams        []goPathParamView
	PathParamsLiteral string
}

type goPathParamView struct {
	Name   string
	GoName string
}

func buildGoServerData(doc *OpenAPI) (*goServerData, error) {
	ops := []goOperationView{}
	for _, p := range doc.Paths() {
		for _, verb := range p.Methods() {
			rawOp, _ := p.Item[verb].(map[string]any)
			id, _ := rawOp["operationId"].(string)
			summary, _ := rawOp["summary"].(string)
			view := goOperationView{
				OperationID:  id,
				GoMethodName: exportedGoName(id),
				Method:       verb,
				MethodUpper:  strings.ToUpper(verb),
				Path:         p.Path,
				Summary:      summary,
			}
			view.PathParams = collectPathParams(p.Path)
			view.PathParamsLiteral = pathParamsLiteral(view.PathParams)
			ops = append(ops, view)
		}
	}
	// Stable ordering: by path then method.
	sort.Slice(ops, func(i, j int) bool {
		if ops[i].Path != ops[j].Path {
			return ops[i].Path < ops[j].Path
		}
		return ops[i].Method < ops[j].Method
	})
	return &goServerData{
		Header:     goGeneratedHeader,
		Operations: ops,
	}, nil
}

// collectPathParams extracts {param} placeholders from a path template.
func collectPathParams(path string) []goPathParamView {
	out := []goPathParamView{}
	for {
		i := strings.IndexRune(path, '{')
		if i < 0 {
			break
		}
		j := strings.IndexRune(path[i:], '}')
		if j < 0 {
			break
		}
		name := path[i+1 : i+j]
		out = append(out, goPathParamView{Name: name, GoName: lowerCamel(name)})
		path = path[i+j+1:]
	}
	return out
}

func pathParamsLiteral(ps []goPathParamView) string {
	if len(ps) == 0 {
		return "nil"
	}
	parts := make([]string, len(ps))
	for i, p := range ps {
		parts[i] = fmt.Sprintf("%q", p.Name)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// --- naming helpers ----------------------------------------------------------

func exportedGoName(s string) string {
	if s == "" {
		return ""
	}
	// camelCase or snake_case → PascalCase
	runes := []rune(s)
	if runes[0] >= 'a' && runes[0] <= 'z' {
		runes[0] -= 32
	}
	out := make([]rune, 0, len(runes))
	for i := 0; i < len(runes); i++ {
		if runes[i] == '_' || runes[i] == '-' {
			i++
			if i < len(runes) {
				r := runes[i]
				if r >= 'a' && r <= 'z' {
					r -= 32
				}
				out = append(out, r)
			}
			continue
		}
		out = append(out, runes[i])
	}
	return string(out)
}

func lowerCamel(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	if runes[0] >= 'A' && runes[0] <= 'Z' {
		runes[0] += 32
	}
	return string(runes)
}

func camelize(value string) string {
	parts := strings.Split(value, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		runes := []rune(p)
		if runes[0] >= 'a' && runes[0] <= 'z' {
			runes[0] -= 32
		}
		parts[i] = string(runes)
	}
	return strings.Join(parts, "")
}

func pluralize(name string) string {
	if strings.HasSuffix(name, "s") {
		return name + "es"
	}
	return name + "s"
}
