package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "// Code generated by backend/cmd/codegen/events; DO NOT EDIT.\n// Source: shared/events.yaml and shared/jobs.yaml — owned by docs/spec/event-and-outbox-contract.\n\n"
const generatedTSHeader = "// Code generated by backend/cmd/codegen/events; DO NOT EDIT.\n// Source: shared/events.yaml and shared/jobs.yaml — owned by docs/spec/event-and-outbox-contract.\n\n"

type EventsSpec struct {
	Version         int          `yaml:"version"`
	SchemaVersion   int          `yaml:"schemaVersion"`
	Envelope        EnvelopeSpec `yaml:"envelope"`
	EventLocalEnums []LocalEnum  `yaml:"eventLocalEnums"`
	Events          []EventSpec  `yaml:"events"`
}

type EnvelopeSpec struct {
	Fields []EnvelopeField `yaml:"fields"`
}

type EnvelopeField struct {
	Name         string   `yaml:"name"`
	Type         string   `yaml:"type"`
	Required     bool     `yaml:"required"`
	SoftRequired bool     `yaml:"softRequired"`
	Values       []string `yaml:"values"`
}

type LocalEnum struct {
	Name        string   `yaml:"name"`
	Description string   `yaml:"description"`
	Values      []string `yaml:"values"`
}

type EventSpec struct {
	Name            string                  `yaml:"name"`
	Version         int                     `yaml:"version"`
	Producer        any                     `yaml:"producer"`
	AggregateType   string                  `yaml:"aggregateType"`
	RequiredPayload map[string]PayloadField `yaml:"requiredPayload"`
	OptionalPayload map[string]PayloadField `yaml:"optionalPayload"`
	PIIBoundary     string                  `yaml:"piiBoundary"`
}

type PayloadField struct {
	Type   string `yaml:"type"`
	Source string `yaml:"source"`
}

type JobsSpec struct {
	Version         int       `yaml:"version"`
	SchemaVersion   int       `yaml:"schemaVersion"`
	APIFacingSubset []string  `yaml:"apiFacingSubset"`
	Jobs            []JobSpec `yaml:"jobs"`
}

type JobSpec struct {
	Canonical      string                  `yaml:"canonical"`
	AsynqTask      string                  `yaml:"asynqTask"`
	APIFacing      bool                    `yaml:"apiFacing"`
	TriggerEvent   string                  `yaml:"triggerEvent"`
	OwnerDomain    string                  `yaml:"ownerDomain"`
	Priority       string                  `yaml:"priority"`
	PayloadSchema  map[string]PayloadField `yaml:"payloadSchema"`
	RedactedFields []string                `yaml:"redactedFields"`
}

var b1EnumValues = map[string][]string{
	"InterviewerRole":      {"generalist", "hr", "hiring_manager", "technical_manager", "peer"},
	"MistakeStatus":        {"open", "improving", "mastered"},
	"PracticeGoal":         {"baseline", "sprint", "fix_mistake", "debrief"},
	"PracticeMode":         {"warmup", "core_interview", "single_drill", "counter_questions", "debrief_replay"},
	"PrivacyRequestStatus": {"queued", "processing", "completed", "failed", "cancelled"},
	"PrivacyRequestType":   {"export", "delete"},
	"ReadinessTier":        {"not_ready", "needs_practice", "basically_ready", "well_prepared"},
	"ReportStatus":         {"queued", "generating", "ready", "failed"},
	"TargetJobParseStatus": {"queued", "processing", "ready", "failed"},
}

func Run(eventsPath, jobsPath, repoRoot string, verbose bool) error {
	eventsData, err := os.ReadFile(eventsPath)
	if err != nil {
		return fmt.Errorf("read events yaml: %w", err)
	}
	jobsData, err := os.ReadFile(jobsPath)
	if err != nil {
		return fmt.Errorf("read jobs yaml: %w", err)
	}
	return RunFromBytes(eventsData, jobsData, repoRoot, verbose)
}

func RunFromBytes(eventsData, jobsData []byte, repoRoot string, verbose bool) error {
	var events EventsSpec
	if err := yaml.Unmarshal(eventsData, &events); err != nil {
		return fmt.Errorf("parse events yaml: %w", err)
	}
	var jobs JobsSpec
	if err := yaml.Unmarshal(jobsData, &jobs); err != nil {
		return fmt.Errorf("parse jobs yaml: %w", err)
	}

	targets := []struct {
		path   string
		render func(*EventsSpec, *JobsSpec) ([]byte, error)
	}{
		{filepath.Join(repoRoot, "backend/internal/shared/events/envelope.go"), renderGoEnvelope},
		{filepath.Join(repoRoot, "backend/internal/shared/events/events.go"), renderGoEvents},
		{filepath.Join(repoRoot, "backend/internal/shared/jobs/jobs.go"), renderGoJobs},
		{filepath.Join(repoRoot, "frontend/src/lib/events/envelope.ts"), renderTSEnvelope},
		{filepath.Join(repoRoot, "frontend/src/lib/events/events.ts"), renderTSEvents},
		{filepath.Join(repoRoot, "frontend/src/lib/jobs/jobs.ts"), renderTSJobs},
		{filepath.Join(repoRoot, "shared/events/baseline/events.v1.json"), renderEventsBaseline},
		{filepath.Join(repoRoot, "shared/jobs/baseline/jobs.v1.json"), renderJobsBaseline},
	}
	for _, event := range events.Events {
		event := event
		targets = append(targets, struct {
			path   string
			render func(*EventsSpec, *JobsSpec) ([]byte, error)
		}{
			path: filepath.Join(repoRoot, "shared/events/schemas", event.Name+".v1.json"),
			render: func(e *EventsSpec, j *JobsSpec) ([]byte, error) {
				return renderEventSchema(e, &event)
			},
		})
	}
	enumRefs := collectEnumRefs(&events)
	refNames := make([]string, 0, len(enumRefs))
	for name := range enumRefs {
		refNames = append(refNames, name)
	}
	sort.Strings(refNames)
	for _, name := range refNames {
		name := name
		targets = append(targets, struct {
			path   string
			render func(*EventsSpec, *JobsSpec) ([]byte, error)
		}{
			path: filepath.Join(repoRoot, "shared/events/refs", name+".json"),
			render: func(e *EventsSpec, j *JobsSpec) ([]byte, error) {
				return renderEnumRef(name, enumRefs[name])
			},
		})
	}

	for _, target := range targets {
		content, err := target.render(&events, &jobs)
		if err != nil {
			return fmt.Errorf("render %s: %w", target.path, err)
		}
		if err := writeIfChanged(target.path, content); err != nil {
			return fmt.Errorf("write %s: %w", target.path, err)
		}
		if verbose {
			fmt.Fprintf(os.Stderr, "rendered %s (%d bytes)\n", target.path, len(content))
		}
	}
	return nil
}

func writeIfChanged(path string, content []byte) error {
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, content) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

func renderGoEnvelope(e *EventsSpec, _ *JobsSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package events\n\n")
	buf.WriteString("import (\n\t\"encoding/json\"\n\t\"time\"\n)\n\n")
	buf.WriteString("type EventName string\n\n")
	buf.WriteString("type Producer string\n\nconst (\n")
	for _, producer := range producerValues(e) {
		fmt.Fprintf(&buf, "\tProducer%s Producer = %q\n", pascal(producer), producer)
	}
	buf.WriteString(")\n\n")
	buf.WriteString("type Envelope struct {\n")
	buf.WriteString("\tEventID string `json:\"eventId\"`\n")
	buf.WriteString("\tEventName EventName `json:\"eventName\"`\n")
	buf.WriteString("\tEventVersion int `json:\"eventVersion\"`\n")
	buf.WriteString("\tAggregateType string `json:\"aggregateType\"`\n")
	buf.WriteString("\tAggregateID string `json:\"aggregateId\"`\n")
	buf.WriteString("\tOccurredAt time.Time `json:\"occurredAt\"`\n")
	buf.WriteString("\tProducer Producer `json:\"producer\"`\n")
	buf.WriteString("\tTraceID *string `json:\"traceId,omitempty\"`\n")
	buf.WriteString("\tPayload json.RawMessage `json:\"payload\"`\n")
	buf.WriteString("}\n\n")
	buf.WriteString("type SoftRequiredWarning struct {\n")
	buf.WriteString("\tField string\n")
	buf.WriteString("\tEventID string\n")
	buf.WriteString("\tEventName EventName\n")
	buf.WriteString("\tMessage string\n")
	buf.WriteString("}\n\n")
	buf.WriteString("func (e Envelope) ValidateForPublish() []SoftRequiredWarning {\n")
	buf.WriteString("\tif e.TraceID != nil && *e.TraceID != \"\" {\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn []SoftRequiredWarning{{Field: \"traceId\", EventID: e.EventID, EventName: e.EventName, Message: \"traceId is soft-required; publish allowed\"}}\n")
	buf.WriteString("}\n\n")
	buf.WriteString("func (e Envelope) MarshalJSON() ([]byte, error) {\n\ttype alias Envelope\n\treturn json.Marshal(alias(e))\n}\n\n")
	buf.WriteString("func (e *Envelope) UnmarshalJSON(data []byte) error {\n\ttype alias Envelope\n\tvar decoded alias\n\tif err := json.Unmarshal(data, &decoded); err != nil { return err }\n\t*e = Envelope(decoded)\n\treturn nil\n}\n")
	return formatGo(buf.Bytes())
}

func renderGoEvents(e *EventsSpec, _ *JobsSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package events\n\n")
	buf.WriteString("import sharedtypes \"github.com/monshunter/easyinterview/backend/internal/shared/types\"\n\n")
	for _, enum := range e.EventLocalEnums {
		fmt.Fprintf(&buf, "type %s string\n\nconst (\n", enum.Name)
		for _, value := range enum.Values {
			fmt.Fprintf(&buf, "\t%s%s %s = %q\n", enum.Name, pascal(value), enum.Name, value)
		}
		buf.WriteString(")\n\n")
	}
	buf.WriteString("const (\n")
	for _, event := range e.Events {
		fmt.Fprintf(&buf, "\tEventName%s EventName = %q\n", eventTypeName(event.Name), event.Name)
	}
	buf.WriteString(")\n\n")
	for _, event := range e.Events {
		fmt.Fprintf(&buf, "type %sPayload struct {\n", eventTypeName(event.Name))
		for _, field := range sortedPayloadFields(event.RequiredPayload) {
			spec := event.RequiredPayload[field]
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", goFieldName(field), goType(spec.Type, false), field)
		}
		for _, field := range sortedPayloadFields(event.OptionalPayload) {
			spec := event.OptionalPayload[field]
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s,omitempty\"`\n", goFieldName(field), goType(spec.Type, true), field)
		}
		buf.WriteString("}\n\n")
	}
	return formatGo(buf.Bytes())
}

func renderGoJobs(_ *EventsSpec, j *JobsSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("package jobs\n\n")
	buf.WriteString("import \"fmt\"\n\n")
	buf.WriteString("type JobType string\n\ntype AsynqTask string\n\nconst (\n")
	for _, job := range j.Jobs {
		fmt.Fprintf(&buf, "\tJobType%s JobType = %q\n", jobTypeName(job.Canonical), job.Canonical)
	}
	buf.WriteString(")\n\nconst (\n")
	for _, job := range j.Jobs {
		fmt.Fprintf(&buf, "\tAsynqTask%s AsynqTask = %q\n", jobTypeName(job.Canonical), job.AsynqTask)
	}
	buf.WriteString(")\n\nvar APIFacingJobTypes = []JobType{\n")
	for _, canonical := range j.APIFacingSubset {
		fmt.Fprintf(&buf, "\tJobType%s,\n", jobTypeName(canonical))
	}
	buf.WriteString("}\n\n")
	if email := findJob(j, "email_dispatch"); email != nil {
		writeStringSlice(&buf, "EmailDispatchAllowedPayloadFields", sortedPayloadFields(email.PayloadSchema))
		writeStringSlice(&buf, "EmailDispatchRedactedFields", email.RedactedFields)
		buf.WriteString("type EmailDispatchPayload map[string]string\n\n")
		buf.WriteString("func BuildEmailDispatchPayload(input map[string]string) (EmailDispatchPayload, error) {\n")
		buf.WriteString("\tallowed := map[string]struct{}{\n")
		for _, field := range sortedPayloadFields(email.PayloadSchema) {
			fmt.Fprintf(&buf, "\t\t%q: {},\n", field)
		}
		buf.WriteString("\t}\n")
		buf.WriteString("\tredacted := map[string]struct{}{\n")
		for _, field := range email.RedactedFields {
			fmt.Fprintf(&buf, "\t\t%q: {},\n", field)
		}
		buf.WriteString("\t}\n")
		buf.WriteString("\tpayload := make(EmailDispatchPayload, len(input))\n")
		buf.WriteString("\tfor field, value := range input {\n")
		buf.WriteString("\t\tif _, forbidden := redacted[field]; forbidden {\n")
		buf.WriteString("\t\t\treturn nil, fmt.Errorf(\"email_dispatch payload field %s is redacted and forbidden\", field)\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tif _, ok := allowed[field]; !ok {\n")
		buf.WriteString("\t\t\treturn nil, fmt.Errorf(\"email_dispatch payload field %s is not allowed\", field)\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tpayload[field] = value\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn payload, nil\n")
		buf.WriteString("}\n")
	}
	return formatGo(buf.Bytes())
}

func renderTSEnvelope(e *EventsSpec, _ *JobsSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	fmt.Fprintf(&buf, "export type Producer = %s;\n\n", tsUnion(producerValues(e)))
	buf.WriteString("export interface SoftRequiredWarning {\n")
	buf.WriteString("  field: 'traceId';\n  eventId: string;\n  eventName: string;\n  message: string;\n}\n\n")
	buf.WriteString("export interface EventEnvelope<TPayload> {\n")
	buf.WriteString("  eventId: string;\n  eventName: string;\n  eventVersion: number;\n  aggregateType: string;\n  aggregateId: string;\n  occurredAt: string;\n  producer: Producer;\n  traceId?: string;\n  payload: TPayload;\n}\n")
	buf.WriteString("\nexport function validateEnvelopeForPublish(envelope: EventEnvelope<unknown>): SoftRequiredWarning[] {\n")
	buf.WriteString("  if (envelope.traceId) {\n    return [];\n  }\n")
	buf.WriteString("  return [{ field: 'traceId', eventId: envelope.eventId, eventName: envelope.eventName, message: 'traceId is soft-required; publish allowed' }];\n")
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

func renderTSEvents(e *EventsSpec, _ *JobsSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	buf.WriteString("import type { InterviewerRole, MistakeStatus, PracticeGoal, PracticeMode, PrivacyRequestStatus, PrivacyRequestType, ReadinessTier, ReportStatus, TargetJobParseStatus } from '../conventions';\n\n")
	for _, enum := range e.EventLocalEnums {
		fmt.Fprintf(&buf, "export type %s = %s;\n\n", enum.Name, tsUnion(enum.Values))
	}
	fmt.Fprintf(&buf, "export type EventName = %s;\n\n", tsUnion(eventNames(e)))
	for _, event := range e.Events {
		fmt.Fprintf(&buf, "export const EVENT_NAME_%s = %q as const;\n", upperSnake(event.Name), event.Name)
	}
	buf.WriteString("\n")
	for _, event := range e.Events {
		fmt.Fprintf(&buf, "export interface %sPayload {\n", eventTypeName(event.Name))
		for _, field := range sortedPayloadFields(event.RequiredPayload) {
			spec := event.RequiredPayload[field]
			fmt.Fprintf(&buf, "  %s: %s;\n", field, tsType(spec.Type))
		}
		for _, field := range sortedPayloadFields(event.OptionalPayload) {
			spec := event.OptionalPayload[field]
			fmt.Fprintf(&buf, "  %s?: %s;\n", field, tsType(spec.Type))
		}
		buf.WriteString("}\n\n")
	}
	buf.WriteString("export interface EventNameToPayload {\n")
	for _, event := range e.Events {
		fmt.Fprintf(&buf, "  %q: %sPayload;\n", event.Name, eventTypeName(event.Name))
	}
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

func renderTSJobs(_ *EventsSpec, j *JobsSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	for _, job := range j.Jobs {
		fmt.Fprintf(&buf, "export const JOB_TYPE_%s = %q as const;\n", upperSnake(job.Canonical), job.Canonical)
	}
	buf.WriteString("\n")
	for _, job := range j.Jobs {
		fmt.Fprintf(&buf, "export const ASYNQ_TASK_%s = %q as const;\n", upperSnake(job.Canonical), job.AsynqTask)
	}
	fmt.Fprintf(&buf, "\nexport const API_FACING_JOB_TYPES = [%s] as const;\n", quotedList(j.APIFacingSubset))
	buf.WriteString("export type JobType = typeof JOB_TYPE_TARGET_IMPORT")
	for _, job := range j.Jobs[1:] {
		fmt.Fprintf(&buf, " | typeof JOB_TYPE_%s", upperSnake(job.Canonical))
	}
	buf.WriteString(";\n")
	if email := findJob(j, "email_dispatch"); email != nil {
		fmt.Fprintf(&buf, "export const EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELDS = [%s] as const;\n", quotedList(sortedPayloadFields(email.PayloadSchema)))
		fmt.Fprintf(&buf, "export const EMAIL_DISPATCH_REDACTED_FIELDS = [%s] as const;\n", quotedList(email.RedactedFields))
		buf.WriteString("export type EmailDispatchPayload = Partial<Record<typeof EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELDS[number], string>>;\n")
		buf.WriteString("const EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELD_SET = new Set<string>(EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELDS);\n")
		buf.WriteString("const EMAIL_DISPATCH_REDACTED_FIELD_SET = new Set<string>(EMAIL_DISPATCH_REDACTED_FIELDS);\n")
		buf.WriteString("export function buildEmailDispatchPayload(input: Record<string, string>): EmailDispatchPayload {\n")
		buf.WriteString("  const payload: Record<string, string> = {};\n")
		buf.WriteString("  for (const [field, value] of Object.entries(input)) {\n")
		buf.WriteString("    if (EMAIL_DISPATCH_REDACTED_FIELD_SET.has(field)) {\n")
		buf.WriteString("      throw new Error(`email_dispatch payload field ${field} is redacted and forbidden`);\n")
		buf.WriteString("    }\n")
		buf.WriteString("    if (!EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELD_SET.has(field)) {\n")
		buf.WriteString("      throw new Error(`email_dispatch payload field ${field} is not allowed`);\n")
		buf.WriteString("    }\n")
		buf.WriteString("    payload[field] = value;\n")
		buf.WriteString("  }\n")
		buf.WriteString("  return payload as EmailDispatchPayload;\n")
		buf.WriteString("}\n")
	}
	return buf.Bytes(), nil
}

func renderEventSchema(_ *EventsSpec, event *EventSpec) ([]byte, error) {
	payloadProps := map[string]any{}
	required := sortedPayloadFields(event.RequiredPayload)
	for _, field := range required {
		payloadProps[field] = jsonSchemaForType(event.RequiredPayload[field].Type)
	}
	for _, field := range sortedPayloadFields(event.OptionalPayload) {
		payloadProps[field] = jsonSchemaForType(event.OptionalPayload[field].Type)
	}
	schema := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id":     "shared/events/schemas/" + event.Name + ".v1.json",
		"title":   event.Name + " v1",
		"type":    "object",
		"required": []string{
			"eventId", "eventName", "eventVersion", "aggregateType", "aggregateId", "occurredAt", "producer", "payload",
		},
		"properties": map[string]any{
			"eventId":       map[string]any{"type": "string", "format": "uuid"},
			"eventName":     map[string]any{"const": event.Name},
			"eventVersion":  map[string]any{"const": event.Version},
			"aggregateType": map[string]any{"const": event.AggregateType},
			"aggregateId":   map[string]any{"type": "string", "format": "uuid"},
			"occurredAt":    map[string]any{"type": "string", "format": "date-time"},
			"producer":      map[string]any{"enum": producerList(event.Producer)},
			"traceId":       map[string]any{"type": "string"},
			"payload": map[string]any{
				"type":                 "object",
				"required":             required,
				"additionalProperties": false,
				"properties":           payloadProps,
			},
		},
		"additionalProperties": false,
	}
	return marshalJSON(schema)
}

func renderEventsBaseline(e *EventsSpec, _ *JobsSpec) ([]byte, error) {
	events := make([]map[string]any, 0, len(e.Events))
	for _, event := range e.Events {
		events = append(events, map[string]any{
			"name":            event.Name,
			"version":         event.Version,
			"producer":        event.Producer,
			"aggregateType":   event.AggregateType,
			"requiredPayload": baselinePayload(event.RequiredPayload),
			"optionalPayload": baselinePayload(event.OptionalPayload),
			"piiBoundary":     event.PIIBoundary,
		})
	}
	localEnums := make([]map[string]any, 0, len(e.EventLocalEnums))
	for _, enum := range e.EventLocalEnums {
		localEnums = append(localEnums, map[string]any{
			"name":        enum.Name,
			"description": enum.Description,
			"values":      enum.Values,
		})
	}
	return marshalJSON(map[string]any{
		"version":         e.Version,
		"schemaVersion":   e.SchemaVersion,
		"eventLocalEnums": localEnums,
		"events":          events,
	})
}

func renderJobsBaseline(_ *EventsSpec, j *JobsSpec) ([]byte, error) {
	jobs := make([]map[string]any, 0, len(j.Jobs))
	for _, job := range j.Jobs {
		entry := map[string]any{
			"canonical":      job.Canonical,
			"asynqTask":      job.AsynqTask,
			"apiFacing":      job.APIFacing,
			"triggerEvent":   job.TriggerEvent,
			"ownerDomain":    job.OwnerDomain,
			"priority":       job.Priority,
			"payloadSchema":  baselinePayload(job.PayloadSchema),
			"redactedFields": job.RedactedFields,
		}
		jobs = append(jobs, entry)
	}
	return marshalJSON(map[string]any{
		"version":         j.Version,
		"schemaVersion":   j.SchemaVersion,
		"apiFacingSubset": j.APIFacingSubset,
		"jobs":            jobs,
	})
}

func baselinePayload(fields map[string]PayloadField) map[string]map[string]string {
	out := make(map[string]map[string]string, len(fields))
	for name, field := range fields {
		out[name] = map[string]string{
			"type":   field.Type,
			"source": field.Source,
		}
		if field.Source == "" {
			delete(out[name], "source")
		}
	}
	return out
}

func renderEnumRef(name string, values []string) ([]byte, error) {
	return marshalJSON(map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id":     "shared/events/refs/" + name + ".json",
		"title":   name,
		"type":    "string",
		"enum":    values,
	})
}

func marshalJSON(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func formatGo(src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\n%s", err, src)
	}
	return formatted, nil
}

func sortedPayloadFields(fields map[string]PayloadField) []string {
	out := make([]string, 0, len(fields))
	for name := range fields {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func eventNames(e *EventsSpec) []string {
	out := make([]string, 0, len(e.Events))
	for _, event := range e.Events {
		out = append(out, event.Name)
	}
	return out
}

func producerValues(e *EventsSpec) []string {
	seen := map[string]bool{}
	for _, field := range e.Envelope.Fields {
		if field.Name == "producer" {
			for _, value := range field.Values {
				seen[value] = true
			}
		}
	}
	out := make([]string, 0, len(seen))
	for value := range seen {
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}

func producerList(value any) []string {
	switch v := value.(type) {
	case string:
		return []string{v}
	case []any:
		out := make([]string, 0, len(v))
		for _, item := range v {
			out = append(out, fmt.Sprint(item))
		}
		return out
	case []string:
		return v
	default:
		return nil
	}
}

func goType(typ string, optional bool) string {
	base := "string"
	switch {
	case typ == "uuidv7", typ == "string", typ == "slug", typ == "bcp47", typ == "opaque_ref":
		base = "string"
	case typ == "string[]":
		base = "[]string"
	case typ == "int":
		base = "int"
	case typ == "bool":
		base = "bool"
	case strings.HasPrefix(typ, "$ref:b1."):
		base = "sharedtypes." + strings.TrimPrefix(typ, "$ref:b1.")
	case strings.HasPrefix(typ, "$ref:event."):
		base = strings.TrimPrefix(typ, "$ref:event.")
	}
	if optional && !strings.HasPrefix(base, "[]") {
		return "*" + base
	}
	return base
}

func tsType(typ string) string {
	switch {
	case typ == "uuidv7", typ == "string", typ == "slug", typ == "bcp47", typ == "opaque_ref":
		return "string"
	case typ == "string[]":
		return "readonly string[]"
	case typ == "int":
		return "number"
	case typ == "bool":
		return "boolean"
	case strings.HasPrefix(typ, "$ref:b1."):
		return strings.TrimPrefix(typ, "$ref:b1.")
	case strings.HasPrefix(typ, "$ref:event."):
		return strings.TrimPrefix(typ, "$ref:event.")
	default:
		return "unknown"
	}
}

func jsonSchemaForType(typ string) map[string]any {
	switch typ {
	case "int":
		return map[string]any{"type": "integer"}
	case "bool":
		return map[string]any{"type": "boolean"}
	case "string[]":
		return map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
	default:
		if strings.HasPrefix(typ, "$ref:b1.") {
			return map[string]any{"$ref": "../refs/" + strings.TrimPrefix(typ, "$ref:b1.") + ".json"}
		}
		if strings.HasPrefix(typ, "$ref:event.") {
			return map[string]any{"$ref": "../refs/" + strings.TrimPrefix(typ, "$ref:event.") + ".json"}
		}
		return map[string]any{"type": "string"}
	}
}

func collectEnumRefs(e *EventsSpec) map[string][]string {
	refs := map[string][]string{}
	for _, enum := range e.EventLocalEnums {
		refs[enum.Name] = enum.Values
	}
	for _, event := range e.Events {
		for _, field := range event.RequiredPayload {
			collectEnumRef(field.Type, refs)
		}
		for _, field := range event.OptionalPayload {
			collectEnumRef(field.Type, refs)
		}
	}
	return refs
}

func collectEnumRef(typ string, refs map[string][]string) {
	if strings.HasPrefix(typ, "$ref:b1.") {
		name := strings.TrimPrefix(typ, "$ref:b1.")
		if values, ok := b1EnumValues[name]; ok {
			refs[name] = values
		}
	}
}

func eventTypeName(name string) string {
	return pascal(strings.ReplaceAll(name, ".", "_"))
}

func jobTypeName(canonical string) string {
	return pascal(canonical)
}

func goFieldName(name string) string {
	out := pascal(camelToSnake(name))
	out = strings.ReplaceAll(out, "Id", "ID")
	return out
}

var camelBoundary = regexp.MustCompile(`([a-z0-9])([A-Z])`)

func camelToSnake(value string) string {
	return strings.ToLower(camelBoundary.ReplaceAllString(value, `${1}_${2}`))
}

func pascal(value string) string {
	parts := regexp.MustCompile(`[._-]`).Split(value, -1)
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func upperSnake(value string) string {
	replaced := strings.NewReplacer(".", "_", "-", "_").Replace(value)
	return strings.ToUpper(camelToSnake(replaced))
}

func tsUnion(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%q", value))
	}
	return strings.Join(parts, " | ")
}

func quotedList(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%q", value))
	}
	return strings.Join(parts, ", ")
}

func writeStringSlice(buf *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(buf, "var %s = []string{\n", name)
	for _, value := range values {
		fmt.Fprintf(buf, "\t%q,\n", value)
	}
	buf.WriteString("}\n\n")
}

func findJob(j *JobsSpec, canonical string) *JobSpec {
	for i := range j.Jobs {
		if j.Jobs[i].Canonical == canonical {
			return &j.Jobs[i]
		}
	}
	return nil
}
