// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

export const TMP_ID_PREFIX = 'tmp_';
export const SAMPLE_UUID_V7 = '0195f2d0-4a44-7fc2-8f77-1f9c4ce1ae9e';

// UUID_V7_REGEX is the canonical UUIDv7 string format used for validation.
export const UUID_V7_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
