// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml, shared/jobs.yaml, and shared/conventions.yaml — owned by docs/spec/event-and-outbox-contract.

export type Producer = "api" | "dispatcher" | "review" | "worker";

export interface SoftRequiredWarning {
  field: 'traceId';
  eventId: string;
  eventName: string;
  message: string;
}

export interface EventEnvelope<TPayload> {
  eventId: string;
  eventName: string;
  eventVersion: number;
  aggregateType: string;
  aggregateId: string;
  occurredAt: string;
  producer: Producer;
  traceId?: string;
  payload: TPayload;
}

export function validateEnvelopeForPublish(envelope: EventEnvelope<unknown>): SoftRequiredWarning[] {
  if (envelope.traceId) {
    return [];
  }
  return [{ field: 'traceId', eventId: envelope.eventId, eventName: envelope.eventName, message: 'traceId is soft-required; publish allowed' }];
}
