// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml and shared/jobs.yaml — owned by docs/spec/event-and-outbox-contract.

export type Producer = "api" | "dispatcher" | "review" | "worker";

export interface EventEnvelope<TPayload> {
  eventId: string;
  eventName: string;
  eventVersion: number;
  aggregateType: string;
  aggregateId: string;
  occurredAt: string;
  producer: Producer;
  traceId?: string;
  payload: TPayload;
}
