// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml, shared/jobs.yaml, and shared/conventions.yaml — owned by docs/spec/event-and-outbox-contract.

import type { PracticeGoal, PrivacyRequestStatus, PrivacyRequestType, ReadinessTier, ReportStatus, TargetJobParseStatus } from '../conventions';

export type TargetImportSourceType = "url" | "text" | "file";

export type ResumeTailorMode = "gap_review" | "bullet_suggestions";

export type SourceFreshnessStatus = "fresh" | "stale" | "failed";

export type EventName = "target.import.requested" | "target.parsed" | "target.analysis.failed" | "practice.session.started" | "practice.session.completed" | "report.generation.requested" | "report.generated" | "report.generation.failed" | "resume.parse.completed" | "resume.tailor.completed" | "source.refreshed" | "privacy.request.created" | "privacy.request.completed";

export const EVENT_NAME_TARGET_IMPORT_REQUESTED = "target.import.requested" as const;
export const EVENT_NAME_TARGET_PARSED = "target.parsed" as const;
export const EVENT_NAME_TARGET_ANALYSIS_FAILED = "target.analysis.failed" as const;
export const EVENT_NAME_PRACTICE_SESSION_STARTED = "practice.session.started" as const;
export const EVENT_NAME_PRACTICE_SESSION_COMPLETED = "practice.session.completed" as const;
export const EVENT_NAME_REPORT_GENERATION_REQUESTED = "report.generation.requested" as const;
export const EVENT_NAME_REPORT_GENERATED = "report.generated" as const;
export const EVENT_NAME_REPORT_GENERATION_FAILED = "report.generation.failed" as const;
export const EVENT_NAME_RESUME_PARSE_COMPLETED = "resume.parse.completed" as const;
export const EVENT_NAME_RESUME_TAILOR_COMPLETED = "resume.tailor.completed" as const;
export const EVENT_NAME_SOURCE_REFRESHED = "source.refreshed" as const;
export const EVENT_NAME_PRIVACY_REQUEST_CREATED = "privacy.request.created" as const;
export const EVENT_NAME_PRIVACY_REQUEST_COMPLETED = "privacy.request.completed" as const;

export interface TargetImportRequestedPayload {
  sourceType: TargetImportSourceType;
  targetJobId: string;
  targetLanguage: string;
  userId: string;
}

export interface TargetParsedPayload {
  analysisStatus: TargetJobParseStatus;
  coreThemes: readonly string[];
  requirementCount: number;
  targetJobId: string;
  userId: string;
}

export interface TargetAnalysisFailedPayload {
  errorCode: string;
  retryable: boolean;
  targetJobId: string;
}

export interface PracticeSessionStartedPayload {
  goal: PracticeGoal;
  language: string;
  planId: string;
  sessionId: string;
  targetJobId: string;
}

export interface PracticeSessionCompletedPayload {
  language: string;
  planId: string;
  sessionId: string;
  targetJobId: string;
}

export interface ReportGenerationRequestedPayload {
  reportId: string;
  sessionId: string;
  targetJobId: string;
}

export interface ReportGeneratedPayload {
  modelId: string;
  preparednessLevel: ReadinessTier;
  promptVersion: string;
  reportId: string;
  rubricVersion: string;
  sessionId: string;
  targetJobId: string;
}

export interface ReportGenerationFailedPayload {
  errorCode: string;
  reportId: string;
  retryable: boolean;
  sessionId: string;
}

export interface ResumeParseCompletedPayload {
  parseStatus: TargetJobParseStatus;
  resumeId: string;
  userId: string;
}

export interface ResumeTailorCompletedPayload {
  mode: ResumeTailorMode;
  resumeId: string;
  status: ReportStatus;
  tailorRunId: string;
  targetJobId: string;
}

export interface SourceRefreshedPayload {
  freshnessStatus: SourceFreshnessStatus;
  ownerId: string;
  ownerType: string;
  sourceRecordId: string;
}

export interface PrivacyRequestCreatedPayload {
  privacyRequestId: string;
  requestType: PrivacyRequestType;
  userId: string;
}

export interface PrivacyRequestCompletedPayload {
  privacyRequestId: string;
  requestType: PrivacyRequestType;
  status: PrivacyRequestStatus;
  userId: string;
}

export interface EventNameToPayload {
  "target.import.requested": TargetImportRequestedPayload;
  "target.parsed": TargetParsedPayload;
  "target.analysis.failed": TargetAnalysisFailedPayload;
  "practice.session.started": PracticeSessionStartedPayload;
  "practice.session.completed": PracticeSessionCompletedPayload;
  "report.generation.requested": ReportGenerationRequestedPayload;
  "report.generated": ReportGeneratedPayload;
  "report.generation.failed": ReportGenerationFailedPayload;
  "resume.parse.completed": ResumeParseCompletedPayload;
  "resume.tailor.completed": ResumeTailorCompletedPayload;
  "source.refreshed": SourceRefreshedPayload;
  "privacy.request.created": PrivacyRequestCreatedPayload;
  "privacy.request.completed": PrivacyRequestCompletedPayload;
}
