// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package errors

// Documented error codes (00-shared-conventions §3.2). All values are
// UPPER_SNAKE_CASE per shared-conventions-codified D-5.
const (
	CodeAuthUnauthorized        = "AUTH_UNAUTHORIZED"
	CodeTargetImportFailed      = "TARGET_IMPORT_FAILED"
	CodePracticeSessionConflict = "PRACTICE_SESSION_CONFLICT"
	CodeReportNotReady          = "REPORT_NOT_READY"
	CodeValidationFailed        = "VALIDATION_FAILED"
	CodeRateLimited             = "RATE_LIMITED"
)

// AllCodes lists every documented error code in declaration order.
var AllCodes = []string{
	CodeAuthUnauthorized,
	CodeTargetImportFailed,
	CodePracticeSessionConflict,
	CodeReportNotReady,
	CodeValidationFailed,
	CodeRateLimited,
}

// CodeMeta holds the documented default message and retryable hint per error code.
type CodeMeta struct {
	Message   string
	Retryable bool
}

// CodeRegistry maps every documented error code to its metadata.
var CodeRegistry = map[string]CodeMeta{
	CodeAuthUnauthorized:        {Message: "authentication required or invalid", Retryable: false},
	CodeTargetImportFailed:      {Message: "failed to import target job", Retryable: true},
	CodePracticeSessionConflict: {Message: "practice session is in conflicting state", Retryable: false},
	CodeReportNotReady:          {Message: "report is not ready yet", Retryable: true},
	CodeValidationFailed:        {Message: "request validation failed", Retryable: false},
	CodeRateLimited:             {Message: "rate limit exceeded", Retryable: true},
}
