// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package errors

// Documented error codes from shared/conventions.yaml. All values are
// UPPER_SNAKE_CASE per shared-conventions-codified D-5.
const (
	CodeAuthUnauthorized              = "AUTH_UNAUTHORIZED"
	CodeTargetImportFailed            = "TARGET_IMPORT_FAILED"
	CodeTargetJobNotFound             = "TARGET_JOB_NOT_FOUND"
	CodeTargetImportSourceInvalid     = "TARGET_IMPORT_SOURCE_INVALID"
	CodeTargetImportSourceUnavailable = "TARGET_IMPORT_SOURCE_UNAVAILABLE"
	CodeTargetInvalidStateTransition  = "TARGET_INVALID_STATE_TRANSITION"
	CodePracticeSessionConflict       = "PRACTICE_SESSION_CONFLICT"
	CodePracticePlanNotFound          = "PRACTICE_PLAN_NOT_FOUND"
	CodePracticeSessionNotFound       = "PRACTICE_SESSION_NOT_FOUND"
	CodeReportNotReady                = "REPORT_NOT_READY"
	CodeResumeExportNotAvailable      = "RESUME_EXPORT_NOT_AVAILABLE"
	CodeValidationFailed              = "VALIDATION_FAILED"
	CodeRateLimited                   = "RATE_LIMITED"
	CodeAiProviderTimeout             = "AI_PROVIDER_TIMEOUT"
	CodeAiOutputInvalid               = "AI_OUTPUT_INVALID"
	CodeAiFallbackExhausted           = "AI_FALLBACK_EXHAUSTED"
	CodeAiUnsupportedCapability       = "AI_UNSUPPORTED_CAPABILITY"
	CodeAiProviderConfigInvalid       = "AI_PROVIDER_CONFIG_INVALID"
	CodeAiProviderSecretMissing       = "AI_PROVIDER_SECRET_MISSING"
)

// AllCodes lists every documented error code in declaration order.
var AllCodes = []string{
	CodeAuthUnauthorized,
	CodeTargetImportFailed,
	CodeTargetJobNotFound,
	CodeTargetImportSourceInvalid,
	CodeTargetImportSourceUnavailable,
	CodeTargetInvalidStateTransition,
	CodePracticeSessionConflict,
	CodePracticePlanNotFound,
	CodePracticeSessionNotFound,
	CodeReportNotReady,
	CodeResumeExportNotAvailable,
	CodeValidationFailed,
	CodeRateLimited,
	CodeAiProviderTimeout,
	CodeAiOutputInvalid,
	CodeAiFallbackExhausted,
	CodeAiUnsupportedCapability,
	CodeAiProviderConfigInvalid,
	CodeAiProviderSecretMissing,
}

// CodeMeta holds the documented default message and retryable hint per error code.
type CodeMeta struct {
	Message   string
	Retryable bool
}

// CodeRegistry maps every documented error code to its metadata.
var CodeRegistry = map[string]CodeMeta{
	CodeAuthUnauthorized:              {Message: "authentication required or invalid", Retryable: false},
	CodeTargetImportFailed:            {Message: "failed to import target job", Retryable: true},
	CodeTargetJobNotFound:             {Message: "target job not found", Retryable: false},
	CodeTargetImportSourceInvalid:     {Message: "target import source is invalid or unreachable per policy", Retryable: false},
	CodeTargetImportSourceUnavailable: {Message: "target import source is temporarily unavailable", Retryable: true},
	CodeTargetInvalidStateTransition:  {Message: "target job state transition is not allowed", Retryable: false},
	CodePracticeSessionConflict:       {Message: "practice session is in conflicting state", Retryable: false},
	CodePracticePlanNotFound:          {Message: "practice plan not found", Retryable: false},
	CodePracticeSessionNotFound:       {Message: "practice session not found", Retryable: false},
	CodeReportNotReady:                {Message: "report is not ready yet", Retryable: true},
	CodeResumeExportNotAvailable:      {Message: "resume version export is not available in P0", Retryable: false},
	CodeValidationFailed:              {Message: "request validation failed", Retryable: false},
	CodeRateLimited:                   {Message: "rate limit exceeded", Retryable: true},
	CodeAiProviderTimeout:             {Message: "AI provider request timed out", Retryable: true},
	CodeAiOutputInvalid:               {Message: "AI output failed schema validation", Retryable: false},
	CodeAiFallbackExhausted:           {Message: "AI fallback chain exhausted", Retryable: true},
	CodeAiUnsupportedCapability:       {Message: "AI capability is not supported", Retryable: false},
	CodeAiProviderConfigInvalid:       {Message: "AI provider registry or model profile configuration is invalid", Retryable: false},
	CodeAiProviderSecretMissing:       {Message: "AI provider secret is missing", Retryable: false},
}
