// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package errors

// Documented error codes from shared/conventions.yaml. All values are
// UPPER_SNAKE_CASE per shared-conventions-codified D-5.
const (
	CodeAuthUnauthorized        = "AUTH_UNAUTHORIZED"
	CodeTargetImportFailed      = "TARGET_IMPORT_FAILED"
	CodePracticeSessionConflict = "PRACTICE_SESSION_CONFLICT"
	CodeReportNotReady          = "REPORT_NOT_READY"
	CodeValidationFailed        = "VALIDATION_FAILED"
	CodeRateLimited             = "RATE_LIMITED"
	CodeAiProviderTimeout       = "AI_PROVIDER_TIMEOUT"
	CodeAiOutputInvalid         = "AI_OUTPUT_INVALID"
	CodeAiFallbackExhausted     = "AI_FALLBACK_EXHAUSTED"
	CodeAiUnsupportedCapability = "AI_UNSUPPORTED_CAPABILITY"
	CodeAiProviderConfigInvalid = "AI_PROVIDER_CONFIG_INVALID"
	CodeAiProviderSecretMissing = "AI_PROVIDER_SECRET_MISSING"
)

// AllCodes lists every documented error code in declaration order.
var AllCodes = []string{
	CodeAuthUnauthorized,
	CodeTargetImportFailed,
	CodePracticeSessionConflict,
	CodeReportNotReady,
	CodeValidationFailed,
	CodeRateLimited,
	CodeAiProviderTimeout,
	CodeAiOutputInvalid,
	CodeAiFallbackExhausted,
	CodeAiUnsupportedCapability,
	CodeAiProviderConfigInvalid,
	CodeAiProviderSecretMissing,
}

// CodeMeta holds the documented default message and retryable hint per error code.
type CodeMeta struct {
	Message   string
	Retryable bool
}

// CodeRegistry maps every documented error code to its metadata.
var CodeRegistry = map[string]CodeMeta{
	CodeAuthUnauthorized:        {Message: "authentication required or invalid", Retryable: false},
	CodeTargetImportFailed:      {Message: "failed to import target job", Retryable: true},
	CodePracticeSessionConflict: {Message: "practice session is in conflicting state", Retryable: false},
	CodeReportNotReady:          {Message: "report is not ready yet", Retryable: true},
	CodeValidationFailed:        {Message: "request validation failed", Retryable: false},
	CodeRateLimited:             {Message: "rate limit exceeded", Retryable: true},
	CodeAiProviderTimeout:       {Message: "AI provider request timed out", Retryable: true},
	CodeAiOutputInvalid:         {Message: "AI output failed schema validation", Retryable: false},
	CodeAiFallbackExhausted:     {Message: "AI fallback chain exhausted", Retryable: true},
	CodeAiUnsupportedCapability: {Message: "AI capability is not supported", Retryable: false},
	CodeAiProviderConfigInvalid: {Message: "AI provider registry or model profile configuration is invalid", Retryable: false},
	CodeAiProviderSecretMissing: {Message: "AI provider secret is missing", Retryable: false},
}
