// Code generated by backend/cmd/codegen/events; DO NOT EDIT.
// Source: shared/events.yaml, shared/jobs.yaml, and shared/conventions.yaml — owned by docs/spec/event-and-outbox-contract.

export const JOB_TYPE_TARGET_IMPORT = "target_import" as const;
export const JOB_TYPE_RESUME_PARSE = "resume_parse" as const;
export const JOB_TYPE_REPORT_GENERATE = "report_generate" as const;
export const JOB_TYPE_RESUME_TAILOR = "resume_tailor" as const;
export const JOB_TYPE_PRIVACY_EXPORT = "privacy_export" as const;
export const JOB_TYPE_PRIVACY_DELETE = "privacy_delete" as const;
export const JOB_TYPE_EMAIL_DISPATCH = "email_dispatch" as const;

export const ASYNQ_TASK_TARGET_IMPORT = "target.import" as const;
export const ASYNQ_TASK_RESUME_PARSE = "resume.parse" as const;
export const ASYNQ_TASK_REPORT_GENERATE = "report.generate" as const;
export const ASYNQ_TASK_RESUME_TAILOR = "resume.tailor" as const;
export const ASYNQ_TASK_PRIVACY_EXPORT = "privacy.export" as const;
export const ASYNQ_TASK_PRIVACY_DELETE = "privacy.delete" as const;
export const ASYNQ_TASK_EMAIL_DISPATCH = "email.dispatch" as const;

export const API_FACING_JOB_TYPES = ["target_import", "resume_parse", "report_generate", "resume_tailor", "privacy_export", "privacy_delete"] as const;
export type JobType = typeof JOB_TYPE_TARGET_IMPORT | typeof JOB_TYPE_RESUME_PARSE | typeof JOB_TYPE_REPORT_GENERATE | typeof JOB_TYPE_RESUME_TAILOR | typeof JOB_TYPE_PRIVACY_EXPORT | typeof JOB_TYPE_PRIVACY_DELETE | typeof JOB_TYPE_EMAIL_DISPATCH;
export const JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB = "trigger_creates_job" as const;
export const JOB_TRIGGER_EVENT_SEMANTIC_SOURCE_EVENT_ONLY = "source_event_only" as const;
export type JobTriggerEventSemantic = typeof JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB | typeof JOB_TRIGGER_EVENT_SEMANTIC_SOURCE_EVENT_ONLY;
export const JOB_TRIGGER_EVENT_SEMANTICS = {
  target_import: JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB,
  resume_parse: JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB,
  report_generate: JOB_TRIGGER_EVENT_SEMANTIC_SOURCE_EVENT_ONLY,
  resume_tailor: JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB,
  privacy_export: JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB,
  privacy_delete: JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB,
  email_dispatch: JOB_TRIGGER_EVENT_SEMANTIC_TRIGGER_CREATES_JOB,
} as const satisfies Record<JobType, JobTriggerEventSemantic>;
export function isSourceEventOnly(jobType: JobType): boolean {
  return JOB_TRIGGER_EVENT_SEMANTICS[jobType] === JOB_TRIGGER_EVENT_SEMANTIC_SOURCE_EVENT_ONLY;
}
export const EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELDS = ["authChallengeId", "dedupeKey", "deliverySecretRef", "locale", "templateKey", "userId"] as const;
export const EMAIL_DISPATCH_REDACTED_FIELDS = ["rawEmailCode", "emailVerificationUrl", "recipientEmail", "recipientEmailHash", "emailBody", "emailSubject"] as const;
export type EmailDispatchPayload = Partial<Record<typeof EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELDS[number], string>>;
const EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELD_SET = new Set<string>(EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELDS);
const EMAIL_DISPATCH_REDACTED_FIELD_SET = new Set<string>(EMAIL_DISPATCH_REDACTED_FIELDS);
export function buildEmailDispatchPayload(input: Record<string, string>): EmailDispatchPayload {
  const payload: Record<string, string> = {};
  for (const [field, value] of Object.entries(input)) {
    if (EMAIL_DISPATCH_REDACTED_FIELD_SET.has(field)) {
      throw new Error(`email_dispatch payload field ${field} is redacted and forbidden`);
    }
    if (!EMAIL_DISPATCH_ALLOWED_PAYLOAD_FIELD_SET.has(field)) {
      throw new Error(`email_dispatch payload field ${field} is not allowed`);
    }
    payload[field] = value;
  }
  return payload as EmailDispatchPayload;
}
