// Mock data for EasyInterview prototype — 贴近 spec 的真实示例
window.EI_DATA = {
  user: {
    name: "林舟",
    email: "lin.zhou@example.com",
    avatar: "LZ",
    locale: "zh-CN",
    years: 5,
    title: "高级前端工程师",
  },

  targetJobs: [
    {
      id: "tj-1",
      title: "资深前端工程师",
      company: "星环科技",
      location: "上海 · 混合办公",
      language: "中文",
      status: "面试中",
      statusTone: "amber",
      level: "P6",
      source: "招聘方邮件",
      updatedAt: "2 小时前",
      readiness: 3, // 0-3: 未就绪 / 基本可面 / 建议再练 / 较为充分
      readinessLabel: "建议再练",
      nextRound: "经理面 · 4月24日 14:00",
      hits: ["React 深度", "性能优化", "可访问性"],
      gaps: ["大型协作案例", "Design System 落地故事"],
      practices: 4,
      mistakes: 3,
      match: 78,
    },
    {
      id: "tj-2",
      title: "Frontend Platform Engineer",
      company: "Lumen Labs",
      location: "远程 · 新加坡时区",
      language: "英文",
      status: "准备中",
      statusTone: "neutral",
      level: "Senior",
      source: "粘贴 JD",
      updatedAt: "昨天",
      readiness: 2,
      readinessLabel: "基本可面",
      nextRound: "HR 初筛 · 待预约",
      hits: ["TypeScript", "Monorepo"],
      gaps: ["英文表达节奏", "Platform 案例"],
      practices: 2,
      mistakes: 5,
      match: 64,
    },
    {
      id: "tj-3",
      title: "技术专家（Web 架构）",
      company: "云栖集团",
      location: "杭州",
      language: "中文",
      status: "草稿",
      statusTone: "muted",
      level: "P7",
      source: "岗位链接",
      updatedAt: "3 天前",
      readiness: 1,
      readinessLabel: "未就绪",
      nextRound: "未安排",
      hits: ["系统设计"],
      gaps: ["跨团队影响", "技术决策案例"],
      practices: 0,
      mistakes: 0,
      match: 52,
    },
  ],

  jdSample: {
    title: "资深前端工程师",
    company: "星环科技",
    mustHave: [
      "5 年以上大型 Web 应用开发经验",
      "精通 React / TypeScript 与现代构建工具链",
      "主导过性能优化与可访问性改造",
    ],
    nice: [
      "Design System / 组件库落地经验",
      "有跨团队技术推动经验",
      "熟悉可观测性与前端监控",
    ],
    hidden: [
      "岗位上下文偏向 B 端复杂表单与数据可视化",
      "团队近期在推 Monorepo + 微前端架构",
      "面试官团队倾向听到可量化的改进故事",
    ],
    rounds: [
      { name: "HR 初筛", focus: "动机、求职节奏、薪资期望" },
      { name: "技术一面", focus: "React 底层、TS 类型设计、性能" },
      { name: "技术二面", focus: "架构决策、大型协作案例" },
      { name: "经理面", focus: "影响力、冲突处理、目标一致性" },
    ],
  },

  questions: [
    {
      id: "q1",
      n: 1,
      topic: "自我介绍",
      prompt: "用 90 秒介绍一下你自己，并说明你为什么对这个岗位感兴趣。",
      tags: ["动机", "岗位相关性"],
      duration: "90s",
    },
    {
      id: "q2",
      n: 2,
      topic: "性能优化",
      prompt: "讲一个你主导过的前端性能优化项目：起点在哪里，你做了什么，最后衡量的结果是什么？",
      tags: ["核心经历", "内容具体性"],
      duration: "3-4 min",
    },
    {
      id: "q3",
      n: 3,
      topic: "协作冲突",
      prompt: "描述一次你和设计或后端在实现方案上分歧较大的情况，你当时是怎么推动对齐的？",
      tags: ["行为题", "协作"],
      duration: "3 min",
    },
    {
      id: "q4",
      n: 4,
      topic: "技术深挖",
      prompt: "如果要在一个已有的复杂表单系统上引入 Design System，你会怎么切、怎么避免大爆炸式重构？",
      tags: ["岗位相关", "架构判断"],
      duration: "4-5 min",
    },
    {
      id: "q5",
      n: 5,
      topic: "反问环节",
      prompt: "你有什么想问我的？（请准备 2-3 个问题）",
      tags: ["反问"],
      duration: "2 min",
    },
  ],

  sessionTranscript: [
    { role: "ai", text: "你好林舟，我会扮演星环科技的技术面试官。准备好后我们就开始。", t: "00:00" },
    { role: "user", text: "好的，我准备好了。", t: "00:12" },
    { role: "ai", text: "第 1 题：用 90 秒介绍一下你自己，并说明你为什么对这个岗位感兴趣。", t: "00:18", qId: "q1" },
    { role: "user", text: "我叫林舟，在电商行业做了 5 年前端，主要做后台系统和复杂表单。我对这个岗位感兴趣是因为…", t: "00:35" },
    { role: "ai", text: "你提到「复杂表单」，能举一个具体场景吗？比如最棘手的那次。", t: "01:42", followUp: true },
    { role: "user", text: "有一个就是我们的订单改价系统，涉及 40+ 字段…", t: "01:55" },
  ],

  report: {
    readiness: 2,
    readinessLabel: "建议再练",
    duration: "22:14",
    completedAt: "今天 15:48",
    round: "技术一面",
    topPriority: "把「性能优化」的故事补上量化结果，并准备一个可迁移的 Design System 落地案例。",
    highlights: [
      { title: "内容有具体场景", body: "订单改价系统的例子真实且有细节，比上次练习更扎实。", evidence: "Q2 00:02:14" },
      { title: "表达节奏稳定", body: "整体语速和停顿没有影响理解，追问时也没有明显慌乱。", evidence: "全程" },
      { title: "对岗位关键词有映射", body: "主动把自己的「B 端表单」经验映射到 JD 里的「数据可视化」。", evidence: "Q1 00:01:03" },
    ],
    issues: [
      {
        title: "缺量化结果",
        severity: "high",
        body: "性能优化的故事没有给出可验证的量化指标（如 LCP 下降多少、FCP 变化、错误率等）。",
        evidence: "Q2 00:03:28",
        suggestion: "用 STAR + 数字结构重讲：起点指标 → 行动 → 结束指标 → 影响范围。",
      },
      {
        title: "追问后有轻微空转",
        severity: "medium",
        body: "被追问「为什么选这个方案而不是 X」时，回答只复述了方案，没有给权衡。",
        evidence: "Q4 00:14:02",
        suggestion: "准备一条「替代方案 + 我为什么没选」的备用表达。",
      },
      {
        title: "反问偏套路",
        severity: "low",
        body: "反问基本停留在「团队规模、技术栈」，没有体现对公司当下业务的关注。",
        evidence: "Q5 00:20:41",
        suggestion: "至少准备一个基于公司最近动态的反问（新业务线、最近发布等）。",
      },
    ],
    dimensions: [
      { name: "内容具体性", state: "达标", score: 72, confidence: "高" },
      { name: "结构清晰度", state: "强项", score: 84, confidence: "高" },
      { name: "岗位相关性", state: "达标", score: 70, confidence: "中" },
      { name: "追问应对", state: "待加强", score: 58, confidence: "中" },
      { name: "自我认知", state: "达标", score: 68, confidence: "中" },
    ],
    perQuestion: [
      {
        qId: "q1", topic: "自我介绍", state: "达标",
        good: "开场 30 秒内抓住了岗位匹配点。",
        missing: "结尾收得有点仓促，没有一句清晰的「所以我适合这个岗位」。",
        frame: "背景 30s → 代表作 40s → 为什么是这个岗位 20s。",
      },
      {
        qId: "q2", topic: "性能优化", state: "待加强",
        good: "选了真实项目，行动描述清楚。",
        missing: "没有量化结果，影响范围模糊。",
        frame: "指标基线 → 假设 → 行动 → 对比指标 → 业务影响。",
      },
      {
        qId: "q4", topic: "Design System 落地", state: "待加强",
        good: "意识到不能一次性重构。",
        missing: "缺替代方案比较、没谈和设计团队的协作节奏。",
        frame: "识别风险 → 分层切入 → 协作机制 → 度量。",
      },
    ],
    nextPractice: [
      "重复技术一面复练时，必须覆盖「性能优化量化」",
      "项目深挖中加入一次「替代方案权衡」追问",
      "反问环节准备 3 个岗位定制问题",
    ],
  }
};
