// Mock data for EasyInterview prototype — 贴近 spec 的真实示例
window.EI_DATA = {
  user: {
    name: "林舟",
    email: "lin.zhou@example.com",
    avatar: "LZ",
    locale: "zh-CN",
    years: 5,
    title: "高级前端工程师",
  },

  targetJobs: [
    {
      id: "tj-1",
      title: "资深前端工程师",
      company: "星环科技",
      location: "上海 · 混合办公",
      language: "中文",
      status: "面试中",
      statusTone: "amber",
      level: "P6",
      source: "招聘方邮件",
      updatedAt: "2 小时前",
      readiness: 3, // 0-3: 未就绪 / 基本可面 / 建议再练 / 较为充分
      readinessLabel: "建议再练",
      nextRound: "经理面 · 4月24日 14:00",
      hits: ["React 深度", "性能优化", "可访问性"],
      gaps: ["大型协作案例", "Design System 落地故事"],
      practices: 4,
      mistakes: 3,
      match: 78,
    },
    {
      id: "tj-2",
      title: "Frontend Platform Engineer",
      company: "Lumen Labs",
      location: "远程 · 新加坡时区",
      language: "英文",
      status: "准备中",
      statusTone: "neutral",
      level: "Senior",
      source: "粘贴 JD",
      updatedAt: "昨天",
      readiness: 2,
      readinessLabel: "基本可面",
      nextRound: "HR 初筛 · 待预约",
      hits: ["TypeScript", "Monorepo"],
      gaps: ["英文表达节奏", "Platform 案例"],
      practices: 2,
      mistakes: 5,
      match: 64,
    },
    {
      id: "tj-3",
      title: "技术专家（Web 架构）",
      company: "云栖集团",
      location: "杭州",
      language: "中文",
      status: "草稿",
      statusTone: "muted",
      level: "P7",
      source: "岗位链接",
      updatedAt: "3 天前",
      readiness: 1,
      readinessLabel: "未就绪",
      nextRound: "未安排",
      hits: ["系统设计"],
      gaps: ["跨团队影响", "技术决策案例"],
      practices: 0,
      mistakes: 0,
      match: 52,
    },
  ],

  jdSample: {
    title: "资深前端工程师",
    company: "星环科技",
    mustHave: [
      "5 年以上大型 Web 应用开发经验",
      "精通 React / TypeScript 与现代构建工具链",
      "主导过性能优化与可访问性改造",
    ],
    nice: [
      "Design System / 组件库落地经验",
      "有跨团队技术推动经验",
      "熟悉可观测性与前端监控",
    ],
    hidden: [
      "岗位上下文偏向 B 端复杂表单与数据可视化",
      "团队近期在推 Monorepo + 微前端架构",
      "面试官团队倾向听到可量化的改进故事",
    ],
    rounds: [
      { name: "HR 初筛", focus: "动机、求职节奏、薪资期望" },
      { name: "技术一面", focus: "React 底层、TS 类型设计、性能" },
      { name: "技术二面", focus: "架构决策、大型协作案例" },
      { name: "经理面", focus: "影响力、冲突处理、目标一致性" },
    ],
  },

  questions: [
    {
      id: "q1",
      n: 1,
      topic: "自我介绍",
      prompt: "用 90 秒介绍一下你自己，并说明你为什么对这个岗位感兴趣。",
      tags: ["动机", "岗位相关性"],
      duration: "90s",
    },
    {
      id: "q2",
      n: 2,
      topic: "性能优化",
      prompt: "讲一个你主导过的前端性能优化项目：起点在哪里，你做了什么，最后衡量的结果是什么？",
      tags: ["核心经历", "内容具体性"],
      duration: "3-4 min",
    },
    {
      id: "q3",
      n: 3,
      topic: "协作冲突",
      prompt: "描述一次你和设计或后端在实现方案上分歧较大的情况，你当时是怎么推动对齐的？",
      tags: ["行为题", "协作"],
      duration: "3 min",
    },
    {
      id: "q4",
      n: 4,
      topic: "技术深挖",
      prompt: "如果要在一个已有的复杂表单系统上引入 Design System，你会怎么切、怎么避免大爆炸式重构？",
      tags: ["岗位相关", "架构判断"],
      duration: "4-5 min",
    },
    {
      id: "q5",
      n: 5,
      topic: "反问环节",
      prompt: "你有什么想问我的？（请准备 2-3 个问题）",
      tags: ["反问"],
      duration: "2 min",
    },
  ],

  sessionTranscript: [
    { role: "ai", text: "你好林舟，我会扮演星环科技的技术面试官。准备好后我们就开始。", t: "00:00" },
    { role: "user", text: "好的，我准备好了。", t: "00:12" },
    { role: "ai", text: "第 1 题：用 90 秒介绍一下你自己，并说明你为什么对这个岗位感兴趣。", t: "00:18", qId: "q1" },
    { role: "user", text: "我叫林舟，在电商行业做了 5 年前端，主要做后台系统和复杂表单。我对这个岗位感兴趣是因为…", t: "00:35" },
    { role: "ai", text: "你提到「复杂表单」，能举一个具体场景吗？比如最棘手的那次。", t: "01:42", followUp: true },
    { role: "user", text: "有一个就是我们的订单改价系统，涉及 40+ 字段…", t: "01:55" },
  ],

  report: {
    readiness: 2,
    readinessLabel: "建议再练",
    duration: "22:14",
    completedAt: "今天 15:48",
    round: "技术一面",
    topPriority: "把「性能优化」的故事补上量化结果，并准备一个可迁移的 Design System 落地案例。",
    highlights: [
      { title: "内容有具体场景", body: "订单改价系统的例子真实且有细节，比上次练习更扎实。", evidence: "Q2 00:02:14" },
      { title: "表达节奏稳定", body: "整体语速和停顿没有影响理解，追问时也没有明显慌乱。", evidence: "全程" },
      { title: "对岗位关键词有映射", body: "主动把自己的「B 端表单」经验映射到 JD 里的「数据可视化」。", evidence: "Q1 00:01:03" },
    ],
    issues: [
      {
        title: "缺量化结果",
        severity: "high",
        body: "性能优化的故事没有给出可验证的量化指标（如 LCP 下降多少、FCP 变化、错误率等）。",
        evidence: "Q2 00:03:28",
        suggestion: "用 STAR + 数字结构重讲：起点指标 → 行动 → 结束指标 → 影响范围。",
      },
      {
        title: "追问后有轻微空转",
        severity: "medium",
        body: "被追问「为什么选这个方案而不是 X」时，回答只复述了方案，没有给权衡。",
        evidence: "Q4 00:14:02",
        suggestion: "准备一条「替代方案 + 我为什么没选」的备用表达。",
      },
      {
        title: "反问偏套路",
        severity: "low",
        body: "反问基本停留在「团队规模、技术栈」，没有体现对公司当下业务的关注。",
        evidence: "Q5 00:20:41",
        suggestion: "至少准备一个基于公司最近动态的反问（新业务线、最近发布等）。",
      },
    ],
    dimensions: [
      { name: "内容具体性", state: "达标", score: 72, confidence: "高" },
      { name: "结构清晰度", state: "强项", score: 84, confidence: "高" },
      { name: "岗位相关性", state: "达标", score: 70, confidence: "中" },
      { name: "追问应对", state: "待加强", score: 58, confidence: "中" },
      { name: "自我认知", state: "达标", score: 68, confidence: "中" },
    ],
    perQuestion: [
      {
        qId: "q1", topic: "自我介绍", state: "达标",
        good: "开场 30 秒内抓住了岗位匹配点。",
        missing: "结尾收得有点仓促，没有一句清晰的「所以我适合这个岗位」。",
        frame: "背景 30s → 代表作 40s → 为什么是这个岗位 20s。",
      },
      {
        qId: "q2", topic: "性能优化", state: "待加强",
        good: "选了真实项目，行动描述清楚。",
        missing: "没有量化结果，影响范围模糊。",
        frame: "指标基线 → 假设 → 行动 → 对比指标 → 业务影响。",
      },
      {
        qId: "q4", topic: "Design System 落地", state: "待加强",
        good: "意识到不能一次性重构。",
        missing: "缺替代方案比较、没谈和设计团队的协作节奏。",
        frame: "识别风险 → 分层切入 → 协作机制 → 度量。",
      },
    ],
    nextPractice: [
      "重复技术一面复练时，必须覆盖「性能优化量化」",
      "项目深挖中加入一次「替代方案权衡」追问",
      "反问环节准备 3 个岗位定制问题",
    ],
  },

  mistakes: [
    {
      id: "m1",
      ability: "性能优化叙述",
      question: "讲一个你主导过的前端性能优化项目",
      lastAttempt: "2026-04-20",
      status: "改善中",
      attempts: 3,
      jd: "星环科技 · 资深前端",
      priority: "高",
    },
    {
      id: "m2",
      ability: "追问下的方案权衡",
      question: "为什么选 X 而不是 Y 方案",
      lastAttempt: "2026-04-19",
      status: "未解决",
      attempts: 1,
      jd: "星环科技 · 资深前端",
      priority: "高",
    },
    {
      id: "m3",
      ability: "反问质量",
      question: "你有什么想问我的？",
      lastAttempt: "2026-04-20",
      status: "改善中",
      attempts: 2,
      jd: "星环科技 · 资深前端",
      priority: "中",
    },
    {
      id: "m4",
      ability: "英文动机表达",
      question: "Why are you interested in this role?",
      lastAttempt: "2026-04-18",
      status: "未解决",
      attempts: 2,
      jd: "Lumen Labs · Platform Eng",
      priority: "中",
    },
    {
      id: "m5",
      ability: "冲突处理",
      question: "讲一次你和同事分歧很大的情况",
      lastAttempt: "2026-04-15",
      status: "已攻克",
      attempts: 4,
      jd: "星环科技 · 资深前端",
      priority: "低",
    },
  ],

  debriefs: [
    {
      id: "d1",
      company: "星环科技",
      round: "技术一面",
      date: "2026-04-18",
      outcome: "通过",
      hotQuestions: ["复杂表单状态管理方案", "你踩过最大的坑", "下一步职业规划"],
      nextAction: "准备经理面 · 目标：影响力案例 + 冲突处理",
    },
    {
      id: "d2",
      company: "Lumen Labs",
      round: "HR 初筛",
      date: "2026-04-12",
      outcome: "进入下一轮",
      hotQuestions: ["Why this role", "Salary expectation"],
      nextAction: "准备英文技术面 · 目标：术语与节奏",
    },
  ],

  resume: {
    version: "v3 · 星环定制",
    match: 78,
    suggestions: [
      {
        type: "rewrite",
        before: "负责订单系统前端开发，提升了用户体验。",
        after: "主导订单改价系统重构（40+ 字段），将 LCP 从 3.2s 降至 1.4s，每日操作错误率下降 38%。",
        reason: "补上可量化的结果，直接对应 JD 里的「性能优化」。",
      },
      {
        type: "add",
        text: "补充一条 Design System 相关经历：你在练习里提到过推动组件库统一，但简历里没有。",
        reason: "JD 的加分项之一，缺一条就会被扣印象分。",
      },
      {
        type: "trim",
        text: "删除「熟悉 Vue、Angular」这一行。",
        reason: "会稀释岗位聚焦，并招来并非强项的追问。",
      },
    ],
  },

  // Promoted from ExperienceLibraryScreen (screens-p1-depth.jsx) so the OpenAPI
  // `prototype-baseline` fixture for `listExperienceCards` can map from a real
  // data section (B2 002). The screen still owns its presentation copy.
  experiences: [
    {
      id: "exp-c1",
      title: "购物车/结账链路重写",
      company: "Acme",
      period: "2024 Q1–Q2",
      situation: "结账 LCP 3.2s；第二步流失约 8%；老的 class 组件栈；无 SSR。",
      task: "把结账链路从 3.2s 降到 1.5s 以内，同时降低第二步流失。",
      action: "提出 RSC + 选择性注水，两周搭出原型；用 feature flag 分 4 波灰度上线。",
      result: "LCP 3.2s → 1.4s；流失率 8% → 4.2%；营收季度 +180 万。",
      skills: ["performance", "ownership", "trade-offs"],
      language: "zh-CN",
    },
    {
      id: "exp-c2",
      title: "Design System 在 5 个产品的落地",
      company: "Acme",
      period: "2023 H2",
      situation: "5 个产品、4 套 UI 库、0 个共享 token。",
      task: "用 6 个月推动跨 5 个产品迁移到统一组件库。",
      action: "搭 tokens + 基础组件；挑一个试点团队；办 3 次推广会；提供结对迁移。",
      result: "6 个月内 4/5 产品迁到 v1；试点 PM 反馈新人上手快 ~50%。",
      skills: ["influence", "cross-team", "design-system"],
      language: "zh-CN",
    },
    {
      id: "exp-c3",
      title: "与设计师的分歧（40 字段表单）",
      company: "Acme",
      period: "2023 Q3",
      situation: "设计想把 40 个运营字段放一屏；我担心认知负荷会拖垮效率。",
      task: "在不破坏关系的前提下用数据说服对方调整方案。",
      action: "跟 6 个真实操作员做影子观察，记录任务耗时和错误率，提出带智能默认的标签页布局。",
      result: "任务耗时 -42%；设计师看完数据认可方案，两周上线。",
      skills: ["conflict-resolution", "user-research", "data-driven"],
      language: "zh-CN",
    },
    {
      id: "exp-c4",
      title: "结账 CTA 颜色的失败 A/B",
      company: "Lumen",
      period: "2021 Q4",
      situation: "以为把 CTA 从橙改绿能提升转化。",
      task: "用一次 A/B 实验验证假设。",
      action: "上线实验，跑两周拿到足够样本量。",
      result: "没有显著差异；学会先看先验、先讲机制，而不是凭感觉做 A/B。",
      skills: ["failure-learning", "ab-testing", "humility"],
      language: "zh-CN",
    },
    {
      id: "exp-c5",
      title: "带起 3 个前端新人",
      company: "Acme",
      period: "2024 Q3–Q4",
      situation: "团队从 4 人扩到 7 人；没有 onboarding 流程。",
      task: "把 3 个新人带到独立产出的水平。",
      action: "建立两周 onboarding checklist；每周 1v1 复盘；安排小型 owner 任务。",
      result: "3 名新人在 6 周内独立交付；后续 onboarding 时长缩短到 2 周以内。",
      skills: ["mentorship", "process-design", "leadership"],
      language: "zh-CN",
    },
  ],

  growth: {
    last30d: {
      practices: 14,
      minutes: 312,
      mistakesResolved: 6,
      mistakesTotal: 12,
    },
    trendDim: [
      { name: "内容具体性", values: [55, 58, 62, 65, 68, 70, 72] },
      { name: "结构清晰度", values: [70, 72, 74, 78, 80, 82, 84] },
      { name: "岗位相关性", values: [45, 50, 58, 62, 64, 68, 70] },
      { name: "追问应对", values: [40, 45, 48, 50, 52, 55, 58] },
      { name: "自我认知", values: [60, 62, 63, 65, 66, 67, 68] },
    ],
    weeks: ["3/10", "3/17", "3/24", "3/31", "4/7", "4/14", "今周"],
    recent: [
      { date: "4/20", job: "星环 · 资深前端", mode: "模拟面试 · 技术一面", readiness: 2 },
      { date: "4/19", job: "星环 · 资深前端", mode: "模拟面试 · 技术一面", readiness: 2 },
      { date: "4/18", job: "Lumen Labs", mode: "模拟面试 · HR 初筛", readiness: 1 },
      { date: "4/17", job: "星环 · 资深前端", mode: "模拟面试 · 技术二面", readiness: 2 },
      { date: "4/15", job: "星环 · 资深前端", mode: "复盘面试 · 技术一面", readiness: 2 },
    ],
  },
};
