// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package ai

// Owner boundary:
// B1 owns field names and validation helpers.
// A3 owns AIClient, AICallMeta runtime fill, Model Profile schema, and provider adapters.
// A4 owns AI_GATEWAY_* connection parameter validation.
// B4 owns typed database columns.
// F1 owns metrics and log consumption.

// FieldName is a B1-owned AI metadata wire field name.
type FieldName string

const (
	FieldModelProfileName    FieldName = "model_profile_name"
	FieldModelProfileVersion FieldName = "model_profile_version"
	FieldModelFamily         FieldName = "model_family"
	FieldModelId             FieldName = "model_id"
	FieldFallbackChain       FieldName = "fallback_chain"
	FieldRoute               FieldName = "route"
	FieldValidationStatus    FieldName = "validation_status"
	FieldOutputSchemaVersion FieldName = "output_schema_version"
	FieldPromptVersion       FieldName = "prompt_version"
	FieldRubricVersion       FieldName = "rubric_version"
	FieldLanguage            FieldName = "language"
	FieldFeatureFlag         FieldName = "feature_flag"
	FieldDataSourceVersion   FieldName = "data_source_version"
)

// AllFieldNames lists every AI metadata field in declaration order.
var AllFieldNames = []FieldName{
	FieldModelProfileName,
	FieldModelProfileVersion,
	FieldModelFamily,
	FieldModelId,
	FieldFallbackChain,
	FieldRoute,
	FieldValidationStatus,
	FieldOutputSchemaVersion,
	FieldPromptVersion,
	FieldRubricVersion,
	FieldLanguage,
	FieldFeatureFlag,
	FieldDataSourceVersion,
}

// IsFieldName reports whether value is a documented AI metadata field name.
func IsFieldName(value string) bool {
	for _, field := range AllFieldNames {
		if string(field) == value {
			return true
		}
	}
	return false
}
