// Code generated by backend/cmd/codegen/conventions; DO NOT EDIT.
// Source: shared/conventions.yaml — owned by docs/spec/shared-conventions-codified.

package ai

// Owner boundary:
// B1 owns field names and validation helpers.
// A3 owns AIClient, AICallMeta runtime fill, Model Profile schema, and provider adapters.
// A4 owns AI_PROVIDER_* connection parameter validation.
// B4 owns typed database columns.
// F1 owns metrics and log consumption.

// Capability is a B1-owned AI capability literal.
type Capability string

const (
	CapabilityChat     Capability = "chat"
	CapabilityStt      Capability = "stt"
	CapabilityRealtime Capability = "realtime"
	CapabilityJudge    Capability = "judge"
)

// AllCapabilities lists every AI capability in declaration order.
var AllCapabilities = []Capability{
	CapabilityChat,
	CapabilityStt,
	CapabilityRealtime,
	CapabilityJudge,
}

// IsCapability reports whether value is a documented AI capability.
func IsCapability(value string) bool {
	for _, capability := range AllCapabilities {
		if string(capability) == value {
			return true
		}
	}
	return false
}

// ProviderRegistryFieldName is a B1-owned AI provider registry field wire field name.
type ProviderRegistryFieldName string

const (
	ProviderRegistryFieldNameName         ProviderRegistryFieldName = "name"
	ProviderRegistryFieldNameProtocol     ProviderRegistryFieldName = "protocol"
	ProviderRegistryFieldNameBaseUrlEnv   ProviderRegistryFieldName = "base_url_env"
	ProviderRegistryFieldNameApiKeyEnv    ProviderRegistryFieldName = "api_key_env"
	ProviderRegistryFieldNameCapabilities ProviderRegistryFieldName = "capabilities"
	ProviderRegistryFieldNameVersion      ProviderRegistryFieldName = "version"
)

// AllProviderRegistryFieldNames lists every AI provider registry field in declaration order.
var AllProviderRegistryFieldNames = []ProviderRegistryFieldName{
	ProviderRegistryFieldNameName,
	ProviderRegistryFieldNameProtocol,
	ProviderRegistryFieldNameBaseUrlEnv,
	ProviderRegistryFieldNameApiKeyEnv,
	ProviderRegistryFieldNameCapabilities,
	ProviderRegistryFieldNameVersion,
}

// IsProviderRegistryFieldName reports whether value is a documented AI provider registry field.
func IsProviderRegistryFieldName(value string) bool {
	for _, field := range AllProviderRegistryFieldNames {
		if string(field) == value {
			return true
		}
	}
	return false
}

// ModelProfileFieldName is a B1-owned AI model profile field wire field name.
type ModelProfileFieldName string

const (
	ModelProfileFieldNameName              ModelProfileFieldName = "name"
	ModelProfileFieldNameCapability        ModelProfileFieldName = "capability"
	ModelProfileFieldNameStatus            ModelProfileFieldName = "status"
	ModelProfileFieldNameUnsupportedReason ModelProfileFieldName = "unsupported_reason"
	ModelProfileFieldNameDefault           ModelProfileFieldName = "default"
	ModelProfileFieldNameProviderRef       ModelProfileFieldName = "provider_ref"
	ModelProfileFieldNameModel             ModelProfileFieldName = "model"
	ModelProfileFieldNameParams            ModelProfileFieldName = "params"
	ModelProfileFieldNameFallback          ModelProfileFieldName = "fallback"
	ModelProfileFieldNameWhen              ModelProfileFieldName = "when"
	ModelProfileFieldNameTimeoutMs         ModelProfileFieldName = "timeout_ms"
	ModelProfileFieldNameMaxTokens         ModelProfileFieldName = "max_tokens"
	ModelProfileFieldNameRateLimit         ModelProfileFieldName = "rate_limit"
	ModelProfileFieldNameRoute             ModelProfileFieldName = "route"
	ModelProfileFieldNameVersion           ModelProfileFieldName = "version"
	ModelProfileFieldNamePrivacyPolicy     ModelProfileFieldName = "privacy_policy"
)

// AllModelProfileFieldNames lists every AI model profile field in declaration order.
var AllModelProfileFieldNames = []ModelProfileFieldName{
	ModelProfileFieldNameName,
	ModelProfileFieldNameCapability,
	ModelProfileFieldNameStatus,
	ModelProfileFieldNameUnsupportedReason,
	ModelProfileFieldNameDefault,
	ModelProfileFieldNameProviderRef,
	ModelProfileFieldNameModel,
	ModelProfileFieldNameParams,
	ModelProfileFieldNameFallback,
	ModelProfileFieldNameWhen,
	ModelProfileFieldNameTimeoutMs,
	ModelProfileFieldNameMaxTokens,
	ModelProfileFieldNameRateLimit,
	ModelProfileFieldNameRoute,
	ModelProfileFieldNameVersion,
	ModelProfileFieldNamePrivacyPolicy,
}

// IsModelProfileFieldName reports whether value is a documented AI model profile field.
func IsModelProfileFieldName(value string) bool {
	for _, field := range AllModelProfileFieldNames {
		if string(field) == value {
			return true
		}
	}
	return false
}

// FieldName is a B1-owned AI metadata wire field name.
type FieldName string

const (
	FieldModelProfileName    FieldName = "model_profile_name"
	FieldModelProfileVersion FieldName = "model_profile_version"
	FieldProvider            FieldName = "provider"
	FieldCapability          FieldName = "capability"
	FieldModelFamily         FieldName = "model_family"
	FieldModelId             FieldName = "model_id"
	FieldFallbackChain       FieldName = "fallback_chain"
	FieldRoute               FieldName = "route"
	FieldValidationStatus    FieldName = "validation_status"
	FieldOutputSchemaVersion FieldName = "output_schema_version"
	FieldPromptVersion       FieldName = "prompt_version"
	FieldRubricVersion       FieldName = "rubric_version"
	FieldLanguage            FieldName = "language"
	FieldFeatureFlag         FieldName = "feature_flag"
	FieldDataSourceVersion   FieldName = "data_source_version"
	FieldFromProvider        FieldName = "from_provider"
	FieldFromModelFamily     FieldName = "from_model_family"
	FieldToProvider          FieldName = "to_provider"
	FieldToModelFamily       FieldName = "to_model_family"
	FieldToolInvocations     FieldName = "tool_invocations"
	FieldPartialMetaReason   FieldName = "partial_meta_reason"
)

// AllFieldNames lists every AI metadata field in declaration order.
var AllFieldNames = []FieldName{
	FieldModelProfileName,
	FieldModelProfileVersion,
	FieldProvider,
	FieldCapability,
	FieldModelFamily,
	FieldModelId,
	FieldFallbackChain,
	FieldRoute,
	FieldValidationStatus,
	FieldOutputSchemaVersion,
	FieldPromptVersion,
	FieldRubricVersion,
	FieldLanguage,
	FieldFeatureFlag,
	FieldDataSourceVersion,
	FieldFromProvider,
	FieldFromModelFamily,
	FieldToProvider,
	FieldToModelFamily,
	FieldToolInvocations,
	FieldPartialMetaReason,
}

// IsFieldName reports whether value is a documented AI metadata field name.
func IsFieldName(value string) bool {
	for _, field := range AllFieldNames {
		if string(field) == value {
			return true
		}
	}
	return false
}
